/*
 *
 * Automatically generated file; DO NOT EDIT.
 * NEMU Configuration Menu
 *
 */
#define CONFIG_ISA_loongarch32r 1
#define CONFIG_DIFFTEST_REF_NAME "none"
#define CONFIG_ENGINE "interpreter"
#define CONFIG_WATCHPOINT 1
#define CONFIG_PC_RESET_OFFSET 0x0
#define CONFIG_MSIZE 0x8000000
#define CONFIG_CC_O2 1
#define CONFIG_MODE_SYSTEM 1
#define CONFIG_MEM_RANDOM 1
#define CONFIG_IRING 1
#define CONFIG_TARGET_SHARE 1
#define CONFIG_TRACE_END 100000
#define CONFIG_MBASE 0x1C000000
#define CONFIG_MTRACE_START 0x1C000000
#define CONFIG_TIMER_GETTIMEOFDAY 1
#define CONFIG_FTRACE 1
#define CONFIG_ENGINE_INTERPRETER 1
#define CONFIG_CC_OPT "-O2"
#define CONFIG_MTRACE 1
#define CONFIG_RT_CHECK 1
#define CONFIG_CC "gcc"
#define CONFIG_MTRACE_END 0x24000000
#define CONFIG_DIFFTEST_REF_PATH "none"
#define CONFIG_BREAKPOINT 1
#define CONFIG_TRACE_START 0
#define CONFIG_CC_GCC 1
#define CONFIG_TRACE 1
#define CONFIG_ISA "loongarch32r"
#define CONFIG_PMEM_GARRAY 1
#define CONFIG_JIRL_RET 1

#define CONFIG_SEED 0
