// Generated by CIRCT unknown git version
module ALU(	// <stdin>:2:10
  input         clock,
                reset,
  input  [18:0] io_alu_op,
  input  [31:0] io_src1,
                io_src2,
  output [31:0] io_res);

  wire        add_sub = io_alu_op[1] | io_alu_op[2] | io_alu_op[3];	// ALU.scala:22:29, :23:29, :24:29, :41:36
  wire [32:0] add_res = {1'h0, io_src1} + {1'h0, {32{add_sub}} ^ io_src2} + {32'h0, add_sub};	// ALU.scala:41:36, :42:{27,33,62,67}, Bitwise.scala:77:12
  wire [31:0] or_res = io_src1 | io_src2;	// ALU.scala:46:27
  wire [62:0] sll_res = {31'h0, io_src1} << io_src2[4:0];	// ALU.scala:49:{27,37}
  wire [63:0] sr_res = {{32{io_src1[31] & io_alu_op[10]}}, io_src1} >> io_src2[4:0];	// ALU.scala:31:29, :43:26, :49:37, :50:39, :51:21, Bitwise.scala:77:12, Cat.scala:33:92
  wire [63:0] mul_pre = {32'h0, io_src1} * {32'h0, io_src2};	// ALU.scala:53:27, Bitwise.scala:77:12
  wire [63:0] _mulh_res_T_2 = {{32{io_src1[31]}}, io_src1} * {{32{io_src2[31]}}, io_src2};	// ALU.scala:56:36
  wire [32:0] _div_res_T_2 = $signed({io_src1[31], io_src1}) / $signed({io_src2[31], io_src2});	// ALU.scala:56:36, :59:35
  wire [31:0] _io_res_T_5 = io_alu_op[4] ? io_src1 & io_src2 : 32'h0;	// ALU.scala:25:29, :45:27, Bitwise.scala:77:12, Mux.scala:27:73
  wire [31:0] _io_res_T_6 = io_alu_op[6] ? or_res : 32'h0;	// ALU.scala:27:29, :46:27, Bitwise.scala:77:12, Mux.scala:27:73
  wire [31:0] _io_res_T_7 = io_alu_op[5] ? ~or_res : 32'h0;	// ALU.scala:26:29, :46:27, :47:19, Bitwise.scala:77:12, Mux.scala:27:73
  wire [31:0] _io_res_T_8 = io_alu_op[7] ? io_src1 ^ io_src2 : 32'h0;	// ALU.scala:28:29, :48:27, Bitwise.scala:77:12, Mux.scala:27:73
  wire [31:0] _GEN = (io_alu_op[10] | io_alu_op[9] ? sr_res[31:0] : 32'h0) | (io_alu_op[0] | io_alu_op[1] ?
                add_res[31:0] : 32'h0) | {_io_res_T_5[31:1] | _io_res_T_6[31:1] | _io_res_T_7[31:1] |
                _io_res_T_8[31:1], io_alu_op[2] & (io_src1[31] & ~(io_src2[31]) | (io_src1[31] ^
                ~(io_src2[31])) & add_res[31]) | io_alu_op[3] & ~(add_res[32]) | _io_res_T_5[0] |
                _io_res_T_6[0] | _io_res_T_7[0] | _io_res_T_8[0]} | (io_alu_op[8] ? sll_res[31:0] : 32'h0)
                | (io_alu_op[11] ? io_src2 : 32'h0) | (io_alu_op[12] ? mul_pre[31:0] : 32'h0);	// ALU.scala:21:29, :22:29, :23:29, :24:29, :29:29, :30:29, :31:29, :32:29, :33:29, :42:62, :43:{26,31,33,41,46,48,77,86}, :44:{20,28}, :49:27, :51:21, :53:27, :54:26, :63:17, :71:17, Bitwise.scala:77:12, Mux.scala:27:73
  wire [31:0] _GEN_0 = (io_alu_op[13] ? _mulh_res_T_2[63:32] : 32'h0) | (io_alu_op[14] ? mul_pre[63:32] : 32'h0) |
                (io_alu_op[15] ? _div_res_T_2[31:0] : 32'h0) | (io_alu_op[17] ? $signed(io_src1) %
                $signed(io_src2) : 32'h0) | (io_alu_op[16] ? io_src1 / io_src2 : 32'h0) | (io_alu_op[18] ?
                io_src1 % io_src2 : 32'h0);	// ALU.scala:34:29, :35:29, :36:29, :37:29, :38:29, :39:29, :53:27, :55:28, :56:{36,53}, :57:28, :58:28, :59:35, :60:35, Bitwise.scala:77:12, Mux.scala:27:73
  assign io_res = _GEN | _GEN_0;	// <stdin>:2:10, Mux.scala:27:73
endmodule

