// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "VMain__Syms.h"


VL_ATTR_COLD void VMain___024root__trace_init_sub__TOP__0(VMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+601,"clock", false,-1);
    tracep->declBit(c+602,"reset", false,-1);
}

VL_ATTR_COLD void VMain___024root__trace_init_sub__TOP__Main__0(VMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_init_sub__TOP__Main__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+75,"clock", false,-1);
    tracep->declBit(c+76,"reset", false,-1);
    tracep->declBit(c+77,"cpucore_clock", false,-1);
    tracep->declBit(c+78,"cpucore_reset", false,-1);
    tracep->declBit(c+79,"cpucore_inst_sram_en", false,-1);
    tracep->declBus(c+565,"cpucore_inst_sram_addr", false,-1, 31,0);
    tracep->declBus(c+123,"cpucore_inst_sram_rdata", false,-1, 31,0);
    tracep->declBit(c+124,"cpucore_data_sram_en", false,-1);
    tracep->declBit(c+125,"cpucore_data_sram_wr", false,-1);
    tracep->declBus(c+314,"cpucore_data_sram_addr", false,-1, 31,0);
    tracep->declBus(c+315,"cpucore_data_sram_wdata", false,-1, 31,0);
    tracep->declBus(c+126,"cpucore_data_sram_wstrb", false,-1, 3,0);
    tracep->declBus(c+316,"cpucore_data_sram_rdata", false,-1, 31,0);
    tracep->declBit(c+127,"dram_en", false,-1);
    tracep->declBit(c+128,"dram_wr", false,-1);
    tracep->declBus(c+317,"dram_addr", false,-1, 31,0);
    tracep->declBus(c+318,"dram_wdata", false,-1, 31,0);
    tracep->declBus(c+129,"dram_wstrb", false,-1, 3,0);
    tracep->declBus(c+319,"dram_rdata", false,-1, 31,0);
    tracep->declBit(c+80,"iram_en", false,-1);
    tracep->declBit(c+1,"iram_wr", false,-1);
    tracep->declBus(c+566,"iram_addr", false,-1, 31,0);
    tracep->declBus(c+2,"iram_wdata", false,-1, 31,0);
    tracep->declBus(c+3,"iram_wstrb", false,-1, 3,0);
    tracep->declBus(c+130,"iram_rdata", false,-1, 31,0);
}

VL_ATTR_COLD void VMain___024root__trace_init_sub__TOP__Main__dram__0(VMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_init_sub__TOP__Main__dram__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+131,"en", false,-1);
    tracep->declBit(c+132,"wr", false,-1);
    tracep->declBus(c+320,"addr", false,-1, 31,0);
    tracep->declBus(c+321,"wdata", false,-1, 31,0);
    tracep->declBus(c+133,"wstrb", false,-1, 3,0);
    tracep->declBus(c+322,"rdata", false,-1, 31,0);
}

VL_ATTR_COLD void VMain___024root__trace_init_sub__TOP__Main__cpucore__0(VMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_init_sub__TOP__Main__cpucore__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+81,"clock", false,-1);
    tracep->declBit(c+82,"reset", false,-1);
    tracep->declBit(c+83,"inst_sram_en", false,-1);
    tracep->declBus(c+567,"inst_sram_addr", false,-1, 31,0);
    tracep->declBus(c+134,"inst_sram_rdata", false,-1, 31,0);
    tracep->declBit(c+135,"data_sram_en", false,-1);
    tracep->declBit(c+136,"data_sram_wr", false,-1);
    tracep->declBus(c+323,"data_sram_addr", false,-1, 31,0);
    tracep->declBus(c+324,"data_sram_wdata", false,-1, 31,0);
    tracep->declBus(c+137,"data_sram_wstrb", false,-1, 3,0);
    tracep->declBus(c+325,"data_sram_rdata", false,-1, 31,0);
    tracep->declBit(c+84,"pIF_clock", false,-1);
    tracep->declBit(c+85,"pIF_reset", false,-1);
    tracep->declBit(c+326,"pIF_br_taken", false,-1);
    tracep->declBus(c+327,"pIF_br_target", false,-1, 31,0);
    tracep->declBit(c+86,"pIF_inst_sram_en", false,-1);
    tracep->declBus(c+568,"pIF_inst_sram_addr", false,-1, 31,0);
    tracep->declBit(c+87,"pIF_tofs_valid", false,-1);
    tracep->declBus(c+569,"pIF_tofs_bits_pc", false,-1, 31,0);
    tracep->declBit(c+88,"IF_tods_valid", false,-1);
    tracep->declBus(c+570,"IF_tods_bits_pc", false,-1, 31,0);
    tracep->declBus(c+138,"IF_tods_bits_inst", false,-1, 31,0);
    tracep->declBus(c+139,"IF_inst_sram_rdata", false,-1, 31,0);
    tracep->declBit(c+89,"IF_fs_valid", false,-1);
    tracep->declBus(c+571,"IF_fs_bits_pc", false,-1, 31,0);
    tracep->declBit(c+90,"ID_clock", false,-1);
    tracep->declBit(c+91,"ID_toes_valid", false,-1);
    tracep->declBus(c+572,"ID_toes_bits_pc", false,-1, 31,0);
    tracep->declBus(c+328,"ID_toes_bits_alu_src1", false,-1, 31,0);
    tracep->declBus(c+329,"ID_toes_bits_alu_src2", false,-1, 31,0);
    tracep->declBus(c+140,"ID_toes_bits_alu_op", false,-1, 4,0);
    tracep->declBus(c+141,"ID_toes_bits_rf_waddr", false,-1, 4,0);
    tracep->declBus(c+142,"ID_toes_bits_mem_we", false,-1, 1,0);
    tracep->declBus(c+143,"ID_toes_bits_inst_name", false,-1, 4,0);
    tracep->declBus(c+330,"ID_toes_bits_mem_wdata", false,-1, 31,0);
    tracep->declBit(c+144,"ID_toes_bits_is_break", false,-1);
    tracep->declBus(c+145,"ID_toes_bits_inst", false,-1, 31,0);
    tracep->declBit(c+92,"ID_ds_valid", false,-1);
    tracep->declBus(c+573,"ID_ds_bits_pc", false,-1, 31,0);
    tracep->declBus(c+146,"ID_ds_bits_inst", false,-1, 31,0);
    tracep->declBus(c+574,"ID_torf_pc", false,-1, 31,0);
    tracep->declBus(c+147,"ID_torf_rf_waddr", false,-1, 4,0);
    tracep->declBus(c+331,"ID_torf_rf_wdata", false,-1, 31,0);
    tracep->declBit(c+148,"ID_torf_is_break", false,-1);
    tracep->declBit(c+93,"ID_torf_valid", false,-1);
    tracep->declBus(c+149,"ID_torf_inst", false,-1, 31,0);
    tracep->declBit(c+332,"ID_br_taken", false,-1);
    tracep->declBus(c+333,"ID_br_target", false,-1, 31,0);
    tracep->declBit(c+94,"EXE_es_valid", false,-1);
    tracep->declBus(c+575,"EXE_es_bits_pc", false,-1, 31,0);
    tracep->declBus(c+334,"EXE_es_bits_alu_src1", false,-1, 31,0);
    tracep->declBus(c+335,"EXE_es_bits_alu_src2", false,-1, 31,0);
    tracep->declBus(c+150,"EXE_es_bits_alu_op", false,-1, 4,0);
    tracep->declBus(c+151,"EXE_es_bits_rf_waddr", false,-1, 4,0);
    tracep->declBus(c+152,"EXE_es_bits_mem_we", false,-1, 1,0);
    tracep->declBus(c+153,"EXE_es_bits_inst_name", false,-1, 4,0);
    tracep->declBus(c+336,"EXE_es_bits_mem_wdata", false,-1, 31,0);
    tracep->declBit(c+154,"EXE_es_bits_is_break", false,-1);
    tracep->declBus(c+155,"EXE_es_bits_inst", false,-1, 31,0);
    tracep->declBit(c+95,"EXE_toms_valid", false,-1);
    tracep->declBus(c+576,"EXE_toms_bits_pc", false,-1, 31,0);
    tracep->declBus(c+337,"EXE_toms_bits_alu_res", false,-1, 31,0);
    tracep->declBus(c+156,"EXE_toms_bits_inst_name", false,-1, 4,0);
    tracep->declBit(c+157,"EXE_toms_bits_res_from_mem", false,-1);
    tracep->declBus(c+158,"EXE_toms_bits_rf_waddr", false,-1, 4,0);
    tracep->declBit(c+159,"EXE_toms_bits_is_break", false,-1);
    tracep->declBus(c+160,"EXE_toms_bits_inst", false,-1, 31,0);
    tracep->declBit(c+161,"EXE_data_sram_en", false,-1);
    tracep->declBit(c+162,"EXE_data_sram_wr", false,-1);
    tracep->declBus(c+338,"EXE_data_sram_addr", false,-1, 31,0);
    tracep->declBus(c+339,"EXE_data_sram_wdata", false,-1, 31,0);
    tracep->declBus(c+163,"EXE_data_sram_wstrb", false,-1, 3,0);
    tracep->declBit(c+96,"MEM_ms_valid", false,-1);
    tracep->declBus(c+577,"MEM_ms_bits_pc", false,-1, 31,0);
    tracep->declBus(c+340,"MEM_ms_bits_alu_res", false,-1, 31,0);
    tracep->declBus(c+164,"MEM_ms_bits_inst_name", false,-1, 4,0);
    tracep->declBit(c+165,"MEM_ms_bits_res_from_mem", false,-1);
    tracep->declBus(c+166,"MEM_ms_bits_rf_waddr", false,-1, 4,0);
    tracep->declBit(c+167,"MEM_ms_bits_is_break", false,-1);
    tracep->declBus(c+168,"MEM_ms_bits_inst", false,-1, 31,0);
    tracep->declBit(c+97,"MEM_tows_valid", false,-1);
    tracep->declBus(c+578,"MEM_tows_bits_pc", false,-1, 31,0);
    tracep->declBus(c+169,"MEM_tows_bits_rf_waddr", false,-1, 4,0);
    tracep->declBus(c+341,"MEM_tows_bits_rf_wdata", false,-1, 31,0);
    tracep->declBit(c+170,"MEM_tows_bits_is_break", false,-1);
    tracep->declBus(c+171,"MEM_tows_bits_inst", false,-1, 31,0);
    tracep->declBus(c+342,"MEM_data_sram_rdata", false,-1, 31,0);
    tracep->declBit(c+98,"WB_ws_valid", false,-1);
    tracep->declBus(c+579,"WB_ws_bits_pc", false,-1, 31,0);
    tracep->declBus(c+172,"WB_ws_bits_rf_waddr", false,-1, 4,0);
    tracep->declBus(c+343,"WB_ws_bits_rf_wdata", false,-1, 31,0);
    tracep->declBit(c+173,"WB_ws_bits_is_break", false,-1);
    tracep->declBus(c+174,"WB_ws_bits_inst", false,-1, 31,0);
    tracep->declBus(c+580,"WB_torf_pc", false,-1, 31,0);
    tracep->declBus(c+175,"WB_torf_rf_waddr", false,-1, 4,0);
    tracep->declBus(c+344,"WB_torf_rf_wdata", false,-1, 31,0);
    tracep->declBit(c+176,"WB_torf_is_break", false,-1);
    tracep->declBit(c+99,"WB_torf_valid", false,-1);
    tracep->declBus(c+177,"WB_torf_inst", false,-1, 31,0);
}

VL_ATTR_COLD void VMain___024root__trace_init_sub__TOP__Main__iram__0(VMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_init_sub__TOP__Main__iram__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+100,"en", false,-1);
    tracep->declBit(c+4,"wr", false,-1);
    tracep->declBus(c+581,"addr", false,-1, 31,0);
    tracep->declBus(c+5,"wdata", false,-1, 31,0);
    tracep->declBus(c+6,"wstrb", false,-1, 3,0);
    tracep->declBus(c+178,"rdata", false,-1, 31,0);
}

VL_ATTR_COLD void VMain___024root__trace_init_sub__TOP__Main__cpucore__pIF__0(VMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_init_sub__TOP__Main__cpucore__pIF__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+101,"clock", false,-1);
    tracep->declBit(c+102,"reset", false,-1);
    tracep->declBit(c+345,"br_taken", false,-1);
    tracep->declBus(c+346,"br_target", false,-1, 31,0);
    tracep->declBit(c+103,"inst_sram_en", false,-1);
    tracep->declBus(c+582,"inst_sram_addr", false,-1, 31,0);
    tracep->declBit(c+104,"tofs_valid", false,-1);
    tracep->declBus(c+583,"tofs_bits_pc", false,-1, 31,0);
    tracep->declBus(c+584,"pc", false,-1, 31,0);
    tracep->declBus(c+585,"snpc", false,-1, 31,0);
}

VL_ATTR_COLD void VMain___024root__trace_init_sub__TOP__Main__cpucore__IF__0(VMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_init_sub__TOP__Main__cpucore__IF__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+105,"tods_valid", false,-1);
    tracep->declBus(c+586,"tods_bits_pc", false,-1, 31,0);
    tracep->declBus(c+179,"tods_bits_inst", false,-1, 31,0);
    tracep->declBus(c+180,"inst_sram_rdata", false,-1, 31,0);
    tracep->declBit(c+106,"fs_valid", false,-1);
    tracep->declBus(c+587,"fs_bits_pc", false,-1, 31,0);
}

VL_ATTR_COLD void VMain___024root__trace_init_sub__TOP__Main__cpucore__ID__0(VMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_init_sub__TOP__Main__cpucore__ID__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+107,"clock", false,-1);
    tracep->declBit(c+108,"toes_valid", false,-1);
    tracep->declBus(c+588,"toes_bits_pc", false,-1, 31,0);
    tracep->declBus(c+347,"toes_bits_alu_src1", false,-1, 31,0);
    tracep->declBus(c+348,"toes_bits_alu_src2", false,-1, 31,0);
    tracep->declBus(c+181,"toes_bits_alu_op", false,-1, 4,0);
    tracep->declBus(c+182,"toes_bits_rf_waddr", false,-1, 4,0);
    tracep->declBus(c+183,"toes_bits_mem_we", false,-1, 1,0);
    tracep->declBus(c+184,"toes_bits_inst_name", false,-1, 4,0);
    tracep->declBus(c+349,"toes_bits_mem_wdata", false,-1, 31,0);
    tracep->declBit(c+185,"toes_bits_is_break", false,-1);
    tracep->declBus(c+186,"toes_bits_inst", false,-1, 31,0);
    tracep->declBit(c+109,"ds_valid", false,-1);
    tracep->declBus(c+589,"ds_bits_pc", false,-1, 31,0);
    tracep->declBus(c+187,"ds_bits_inst", false,-1, 31,0);
    tracep->declBus(c+590,"torf_pc", false,-1, 31,0);
    tracep->declBus(c+188,"torf_rf_waddr", false,-1, 4,0);
    tracep->declBus(c+350,"torf_rf_wdata", false,-1, 31,0);
    tracep->declBit(c+189,"torf_is_break", false,-1);
    tracep->declBit(c+110,"torf_valid", false,-1);
    tracep->declBus(c+190,"torf_inst", false,-1, 31,0);
    tracep->declBit(c+351,"br_taken", false,-1);
    tracep->declBus(c+352,"br_target", false,-1, 31,0);
    tracep->declBit(c+111,"reg__clock", false,-1);
    tracep->declBus(c+191,"reg__io_raddr1", false,-1, 4,0);
    tracep->declBus(c+192,"reg__io_raddr2", false,-1, 4,0);
    tracep->declBus(c+353,"reg__io_rdata1", false,-1, 31,0);
    tracep->declBus(c+354,"reg__io_rdata2", false,-1, 31,0);
    tracep->declBus(c+193,"reg__io_waddr", false,-1, 4,0);
    tracep->declBus(c+355,"reg__io_wdata", false,-1, 31,0);
    tracep->declBus(c+591,"reg__io_rf_pc", false,-1, 31,0);
    tracep->declBit(c+194,"reg__io_is_break", false,-1);
    tracep->declBit(c+112,"reg__io_valid", false,-1);
    tracep->declBus(c+195,"reg__io_inst", false,-1, 31,0);
    tracep->declBus(c+196,"rd", false,-1, 4,0);
    tracep->declBus(c+197,"rk", false,-1, 4,0);
    tracep->declBus(c+198,"imm12u", false,-1, 11,0);
    tracep->declBus(c+199,"imm12", false,-1, 31,0);
    tracep->declBus(c+200,"imm20", false,-1, 31,0);
    tracep->declBus(c+201,"decode_res_invInputs", false,-1, 31,0);
    tracep->declBit(c+202,"decode_res_andMatrixInput_0", false,-1);
    tracep->declBit(c+203,"decode_res_andMatrixInput_1", false,-1);
    tracep->declBit(c+204,"decode_res_andMatrixInput_2", false,-1);
    tracep->declBit(c+205,"decode_res_andMatrixInput_3", false,-1);
    tracep->declBit(c+206,"decode_res_andMatrixInput_4", false,-1);
    tracep->declBit(c+207,"decode_res_andMatrixInput_5", false,-1);
    tracep->declBit(c+208,"decode_res_andMatrixInput_6", false,-1);
    tracep->declBit(c+209,"decode_res_andMatrixInput_7", false,-1);
    tracep->declBit(c+210,"decode_res_andMatrixInput_8", false,-1);
    tracep->declBit(c+211,"decode_res_andMatrixInput_9", false,-1);
    tracep->declBit(c+212,"decode_res_andMatrixInput_10", false,-1);
    tracep->declBit(c+213,"decode_res_andMatrixInput_11", false,-1);
    tracep->declBit(c+214,"decode_res_andMatrixInput_12", false,-1);
    tracep->declBit(c+215,"decode_res_andMatrixInput_13", false,-1);
    tracep->declBit(c+216,"decode_res_andMatrixInput_14", false,-1);
    tracep->declBus(c+217,"decode_res_lo", false,-1, 6,0);
    tracep->declBit(c+218,"decode_res_andMatrixInput_3_1", false,-1);
    tracep->declBus(c+219,"decode_res_lo_1", false,-1, 7,0);
    tracep->declBit(c+220,"decode_res_andMatrixInput_2_2", false,-1);
    tracep->declBit(c+221,"decode_res_andMatrixInput_1_4", false,-1);
    tracep->declBit(c+222,"decode_res_andMatrixInput_1_5", false,-1);
    tracep->declBit(c+223,"decode_res_andMatrixInput_0_7", false,-1);
    tracep->declBit(c+224,"decode_res_andMatrixInput_2_8", false,-1);
    tracep->declBit(c+225,"decode_res_andMatrixInput_3_18", false,-1);
    tracep->declBit(c+226,"decode_res_andMatrixInput_3_23", false,-1);
    tracep->declBit(c+227,"decode_res_andMatrixInput_4_23", false,-1);
    tracep->declBit(c+228,"decode_res_andMatrixInput_6_27", false,-1);
    tracep->declBit(c+229,"decode_res_andMatrixInput_2_31", false,-1);
    tracep->declBit(c+230,"decode_res_andMatrixInput_1_35", false,-1);
    tracep->declBit(c+231,"decode_res_andMatrixInput_1_36", false,-1);
    tracep->declBit(c+232,"decode_res_andMatrixInput_1_41", false,-1);
    tracep->declBit(c+233,"decode_res_andMatrixInput_2_41", false,-1);
    tracep->declBit(c+234,"decode_res_andMatrixInput_2_43", false,-1);
    tracep->declBit(c+235,"decode_res_andMatrixInput_5_44", false,-1);
    tracep->declBit(c+236,"decode_res_andMatrixInput_3_57", false,-1);
    tracep->declBus(c+237,"decode_res_orMatrixOutputs_lo", false,-1, 7,0);
    tracep->declBus(c+238,"decode_res_orMatrixOutputs_hi_5", false,-1, 2,0);
    tracep->declBus(c+239,"decode_res_orMatrixOutputs_lo_6", false,-1, 6,0);
    tracep->declBus(c+240,"decode_res_orMatrixOutputs_lo_9", false,-1, 7,0);
    tracep->declBus(c+241,"decode_res_orMatrixOutputs_lo_10", false,-1, 5,0);
    tracep->declBus(c+242,"decode_res_orMatrixOutputs_lo_13", false,-1, 7,0);
    tracep->declBus(c+243,"decode_res_orMatrixOutputs", false,-1, 16,0);
    tracep->declBus(c+244,"decode_res_invMatrixOutputs_lo", false,-1, 7,0);
    tracep->declBus(c+245,"decode_res_invMatrixOutputs", false,-1, 16,0);
    tracep->declBus(c+246,"inst_type", false,-1, 3,0);
    tracep->declBus(c+247,"mem_we", false,-1, 1,0);
    tracep->declBus(c+248,"inst_name", false,-1, 4,0);
    tracep->declBus(c+249,"imm", false,-1, 31,0);
    tracep->declBit(c+250,"rk_or_rd", false,-1);
    tracep->declBit(c+356,"rj_eq_rd", false,-1);
    tracep->declQuad(c+357,"rj_sub_rd", false,-1, 32,0);
    tracep->declBit(c+359,"slt_res", false,-1);
    tracep->declBit(c+360,"sltu_res", false,-1);
    tracep->declBit(c+251,"src1_is_pc", false,-1);
}

VL_ATTR_COLD void VMain___024root__trace_init_sub__TOP__Main__cpucore__EXE__0(VMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_init_sub__TOP__Main__cpucore__EXE__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+113,"es_valid", false,-1);
    tracep->declBus(c+592,"es_bits_pc", false,-1, 31,0);
    tracep->declBus(c+361,"es_bits_alu_src1", false,-1, 31,0);
    tracep->declBus(c+362,"es_bits_alu_src2", false,-1, 31,0);
    tracep->declBus(c+252,"es_bits_alu_op", false,-1, 4,0);
    tracep->declBus(c+253,"es_bits_rf_waddr", false,-1, 4,0);
    tracep->declBus(c+254,"es_bits_mem_we", false,-1, 1,0);
    tracep->declBus(c+255,"es_bits_inst_name", false,-1, 4,0);
    tracep->declBus(c+363,"es_bits_mem_wdata", false,-1, 31,0);
    tracep->declBit(c+256,"es_bits_is_break", false,-1);
    tracep->declBus(c+257,"es_bits_inst", false,-1, 31,0);
    tracep->declBit(c+114,"toms_valid", false,-1);
    tracep->declBus(c+593,"toms_bits_pc", false,-1, 31,0);
    tracep->declBus(c+364,"toms_bits_alu_res", false,-1, 31,0);
    tracep->declBus(c+258,"toms_bits_inst_name", false,-1, 4,0);
    tracep->declBit(c+259,"toms_bits_res_from_mem", false,-1);
    tracep->declBus(c+260,"toms_bits_rf_waddr", false,-1, 4,0);
    tracep->declBit(c+261,"toms_bits_is_break", false,-1);
    tracep->declBus(c+262,"toms_bits_inst", false,-1, 31,0);
    tracep->declBit(c+263,"data_sram_en", false,-1);
    tracep->declBit(c+264,"data_sram_wr", false,-1);
    tracep->declBus(c+365,"data_sram_addr", false,-1, 31,0);
    tracep->declBus(c+366,"data_sram_wdata", false,-1, 31,0);
    tracep->declBus(c+265,"data_sram_wstrb", false,-1, 3,0);
    tracep->declBus(c+266,"alu_io_alu_op", false,-1, 4,0);
    tracep->declBus(c+367,"alu_io_src1", false,-1, 31,0);
    tracep->declBus(c+368,"alu_io_src2", false,-1, 31,0);
    tracep->declBus(c+369,"alu_io_res", false,-1, 31,0);
}

VL_ATTR_COLD void VMain___024root__trace_init_sub__TOP__Main__cpucore__MEM__0(VMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_init_sub__TOP__Main__cpucore__MEM__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+115,"ms_valid", false,-1);
    tracep->declBus(c+594,"ms_bits_pc", false,-1, 31,0);
    tracep->declBus(c+370,"ms_bits_alu_res", false,-1, 31,0);
    tracep->declBus(c+267,"ms_bits_inst_name", false,-1, 4,0);
    tracep->declBit(c+268,"ms_bits_res_from_mem", false,-1);
    tracep->declBus(c+269,"ms_bits_rf_waddr", false,-1, 4,0);
    tracep->declBit(c+270,"ms_bits_is_break", false,-1);
    tracep->declBus(c+271,"ms_bits_inst", false,-1, 31,0);
    tracep->declBit(c+116,"tows_valid", false,-1);
    tracep->declBus(c+595,"tows_bits_pc", false,-1, 31,0);
    tracep->declBus(c+272,"tows_bits_rf_waddr", false,-1, 4,0);
    tracep->declBus(c+371,"tows_bits_rf_wdata", false,-1, 31,0);
    tracep->declBit(c+273,"tows_bits_is_break", false,-1);
    tracep->declBus(c+274,"tows_bits_inst", false,-1, 31,0);
    tracep->declBus(c+372,"data_sram_rdata", false,-1, 31,0);
    tracep->declBus(c+373,"mem_rdata", false,-1, 31,0);
}

VL_ATTR_COLD void VMain___024root__trace_init_sub__TOP__Main__cpucore__WB__0(VMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_init_sub__TOP__Main__cpucore__WB__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+117,"ws_valid", false,-1);
    tracep->declBus(c+596,"ws_bits_pc", false,-1, 31,0);
    tracep->declBus(c+275,"ws_bits_rf_waddr", false,-1, 4,0);
    tracep->declBus(c+374,"ws_bits_rf_wdata", false,-1, 31,0);
    tracep->declBit(c+276,"ws_bits_is_break", false,-1);
    tracep->declBus(c+277,"ws_bits_inst", false,-1, 31,0);
    tracep->declBus(c+597,"torf_pc", false,-1, 31,0);
    tracep->declBus(c+278,"torf_rf_waddr", false,-1, 4,0);
    tracep->declBus(c+375,"torf_rf_wdata", false,-1, 31,0);
    tracep->declBit(c+279,"torf_is_break", false,-1);
    tracep->declBit(c+118,"torf_valid", false,-1);
    tracep->declBus(c+280,"torf_inst", false,-1, 31,0);
}

VL_ATTR_COLD void VMain___024root__trace_init_sub__TOP__Main__cpucore__ID__reg___0(VMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_init_sub__TOP__Main__cpucore__ID__reg___0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+119,"clock", false,-1);
    tracep->declBus(c+281,"io_raddr1", false,-1, 4,0);
    tracep->declBus(c+282,"io_raddr2", false,-1, 4,0);
    tracep->declBus(c+376,"io_rdata1", false,-1, 31,0);
    tracep->declBus(c+377,"io_rdata2", false,-1, 31,0);
    tracep->declBus(c+283,"io_waddr", false,-1, 4,0);
    tracep->declBus(c+378,"io_wdata", false,-1, 31,0);
    tracep->declBus(c+598,"io_rf_pc", false,-1, 31,0);
    tracep->declBit(c+284,"io_is_break", false,-1);
    tracep->declBit(c+120,"io_valid", false,-1);
    tracep->declBus(c+285,"io_inst", false,-1, 31,0);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+408+i*1,"rf", true,(i+0), 31,0);
    }
    tracep->declBit(c+7,"rf_io_rdata1_MPORT_en", false,-1);
    tracep->declBus(c+286,"rf_io_rdata1_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+379,"rf_io_rdata1_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+8,"rf_io_rdata2_MPORT_en", false,-1);
    tracep->declBus(c+287,"rf_io_rdata2_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+380,"rf_io_rdata2_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+9,"rf_difftest_io_rf_1_MPORT_en", false,-1);
    tracep->declBus(c+10,"rf_difftest_io_rf_1_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+440,"rf_difftest_io_rf_1_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+11,"rf_difftest_io_rf_2_MPORT_en", false,-1);
    tracep->declBus(c+12,"rf_difftest_io_rf_2_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+441,"rf_difftest_io_rf_2_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+13,"rf_difftest_io_rf_3_MPORT_en", false,-1);
    tracep->declBus(c+14,"rf_difftest_io_rf_3_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+442,"rf_difftest_io_rf_3_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+15,"rf_difftest_io_rf_4_MPORT_en", false,-1);
    tracep->declBus(c+16,"rf_difftest_io_rf_4_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+443,"rf_difftest_io_rf_4_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+17,"rf_difftest_io_rf_5_MPORT_en", false,-1);
    tracep->declBus(c+18,"rf_difftest_io_rf_5_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+444,"rf_difftest_io_rf_5_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+19,"rf_difftest_io_rf_6_MPORT_en", false,-1);
    tracep->declBus(c+20,"rf_difftest_io_rf_6_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+445,"rf_difftest_io_rf_6_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+21,"rf_difftest_io_rf_7_MPORT_en", false,-1);
    tracep->declBus(c+22,"rf_difftest_io_rf_7_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+446,"rf_difftest_io_rf_7_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+23,"rf_difftest_io_rf_8_MPORT_en", false,-1);
    tracep->declBus(c+24,"rf_difftest_io_rf_8_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+447,"rf_difftest_io_rf_8_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+25,"rf_difftest_io_rf_9_MPORT_en", false,-1);
    tracep->declBus(c+26,"rf_difftest_io_rf_9_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+448,"rf_difftest_io_rf_9_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+27,"rf_difftest_io_rf_10_MPORT_en", false,-1);
    tracep->declBus(c+28,"rf_difftest_io_rf_10_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+449,"rf_difftest_io_rf_10_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+29,"rf_difftest_io_rf_11_MPORT_en", false,-1);
    tracep->declBus(c+30,"rf_difftest_io_rf_11_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+450,"rf_difftest_io_rf_11_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+31,"rf_difftest_io_rf_12_MPORT_en", false,-1);
    tracep->declBus(c+32,"rf_difftest_io_rf_12_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+451,"rf_difftest_io_rf_12_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+33,"rf_difftest_io_rf_13_MPORT_en", false,-1);
    tracep->declBus(c+34,"rf_difftest_io_rf_13_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+452,"rf_difftest_io_rf_13_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+35,"rf_difftest_io_rf_14_MPORT_en", false,-1);
    tracep->declBus(c+36,"rf_difftest_io_rf_14_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+453,"rf_difftest_io_rf_14_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+37,"rf_difftest_io_rf_15_MPORT_en", false,-1);
    tracep->declBus(c+38,"rf_difftest_io_rf_15_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+454,"rf_difftest_io_rf_15_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+39,"rf_difftest_io_rf_16_MPORT_en", false,-1);
    tracep->declBus(c+40,"rf_difftest_io_rf_16_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+455,"rf_difftest_io_rf_16_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+41,"rf_difftest_io_rf_17_MPORT_en", false,-1);
    tracep->declBus(c+42,"rf_difftest_io_rf_17_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+456,"rf_difftest_io_rf_17_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+43,"rf_difftest_io_rf_18_MPORT_en", false,-1);
    tracep->declBus(c+44,"rf_difftest_io_rf_18_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+457,"rf_difftest_io_rf_18_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+45,"rf_difftest_io_rf_19_MPORT_en", false,-1);
    tracep->declBus(c+46,"rf_difftest_io_rf_19_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+458,"rf_difftest_io_rf_19_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+47,"rf_difftest_io_rf_20_MPORT_en", false,-1);
    tracep->declBus(c+48,"rf_difftest_io_rf_20_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+459,"rf_difftest_io_rf_20_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+49,"rf_difftest_io_rf_21_MPORT_en", false,-1);
    tracep->declBus(c+50,"rf_difftest_io_rf_21_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+460,"rf_difftest_io_rf_21_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+51,"rf_difftest_io_rf_22_MPORT_en", false,-1);
    tracep->declBus(c+52,"rf_difftest_io_rf_22_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+461,"rf_difftest_io_rf_22_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+53,"rf_difftest_io_rf_23_MPORT_en", false,-1);
    tracep->declBus(c+54,"rf_difftest_io_rf_23_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+462,"rf_difftest_io_rf_23_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+55,"rf_difftest_io_rf_24_MPORT_en", false,-1);
    tracep->declBus(c+56,"rf_difftest_io_rf_24_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+463,"rf_difftest_io_rf_24_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+57,"rf_difftest_io_rf_25_MPORT_en", false,-1);
    tracep->declBus(c+58,"rf_difftest_io_rf_25_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+464,"rf_difftest_io_rf_25_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+59,"rf_difftest_io_rf_26_MPORT_en", false,-1);
    tracep->declBus(c+60,"rf_difftest_io_rf_26_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+465,"rf_difftest_io_rf_26_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+61,"rf_difftest_io_rf_27_MPORT_en", false,-1);
    tracep->declBus(c+62,"rf_difftest_io_rf_27_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+466,"rf_difftest_io_rf_27_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+63,"rf_difftest_io_rf_28_MPORT_en", false,-1);
    tracep->declBus(c+64,"rf_difftest_io_rf_28_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+467,"rf_difftest_io_rf_28_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+65,"rf_difftest_io_rf_29_MPORT_en", false,-1);
    tracep->declBus(c+66,"rf_difftest_io_rf_29_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+468,"rf_difftest_io_rf_29_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+67,"rf_difftest_io_rf_30_MPORT_en", false,-1);
    tracep->declBus(c+68,"rf_difftest_io_rf_30_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+469,"rf_difftest_io_rf_30_MPORT_data", false,-1, 31,0);
    tracep->declBit(c+69,"rf_difftest_io_rf_31_MPORT_en", false,-1);
    tracep->declBus(c+70,"rf_difftest_io_rf_31_MPORT_addr", false,-1, 4,0);
    tracep->declBus(c+470,"rf_difftest_io_rf_31_MPORT_data", false,-1, 31,0);
    tracep->declBus(c+381,"rf_MPORT_data", false,-1, 31,0);
    tracep->declBus(c+288,"rf_MPORT_addr", false,-1, 4,0);
    tracep->declBit(c+71,"rf_MPORT_mask", false,-1);
    tracep->declBit(c+72,"rf_MPORT_en", false,-1);
    tracep->declBus(c+73,"difftest_rf_0", false,-1, 31,0);
    tracep->declBus(c+471,"difftest_rf_1", false,-1, 31,0);
    tracep->declBus(c+472,"difftest_rf_2", false,-1, 31,0);
    tracep->declBus(c+473,"difftest_rf_3", false,-1, 31,0);
    tracep->declBus(c+474,"difftest_rf_4", false,-1, 31,0);
    tracep->declBus(c+475,"difftest_rf_5", false,-1, 31,0);
    tracep->declBus(c+476,"difftest_rf_6", false,-1, 31,0);
    tracep->declBus(c+477,"difftest_rf_7", false,-1, 31,0);
    tracep->declBus(c+478,"difftest_rf_8", false,-1, 31,0);
    tracep->declBus(c+479,"difftest_rf_9", false,-1, 31,0);
    tracep->declBus(c+480,"difftest_rf_10", false,-1, 31,0);
    tracep->declBus(c+481,"difftest_rf_11", false,-1, 31,0);
    tracep->declBus(c+482,"difftest_rf_12", false,-1, 31,0);
    tracep->declBus(c+483,"difftest_rf_13", false,-1, 31,0);
    tracep->declBus(c+484,"difftest_rf_14", false,-1, 31,0);
    tracep->declBus(c+485,"difftest_rf_15", false,-1, 31,0);
    tracep->declBus(c+486,"difftest_rf_16", false,-1, 31,0);
    tracep->declBus(c+487,"difftest_rf_17", false,-1, 31,0);
    tracep->declBus(c+488,"difftest_rf_18", false,-1, 31,0);
    tracep->declBus(c+489,"difftest_rf_19", false,-1, 31,0);
    tracep->declBus(c+490,"difftest_rf_20", false,-1, 31,0);
    tracep->declBus(c+491,"difftest_rf_21", false,-1, 31,0);
    tracep->declBus(c+492,"difftest_rf_22", false,-1, 31,0);
    tracep->declBus(c+493,"difftest_rf_23", false,-1, 31,0);
    tracep->declBus(c+494,"difftest_rf_24", false,-1, 31,0);
    tracep->declBus(c+495,"difftest_rf_25", false,-1, 31,0);
    tracep->declBus(c+496,"difftest_rf_26", false,-1, 31,0);
    tracep->declBus(c+497,"difftest_rf_27", false,-1, 31,0);
    tracep->declBus(c+498,"difftest_rf_28", false,-1, 31,0);
    tracep->declBus(c+499,"difftest_rf_29", false,-1, 31,0);
    tracep->declBus(c+500,"difftest_rf_30", false,-1, 31,0);
    tracep->declBus(c+501,"difftest_rf_31", false,-1, 31,0);
    tracep->declBit(c+289,"npc_brk_is_break", false,-1);
    tracep->declBit(c+121,"inst_exec_once_valid", false,-1);
    tracep->declBus(c+290,"inst_exec_once_inst", false,-1, 31,0);
    tracep->declBus(c+599,"inst_exec_once_pc", false,-1, 31,0);
}

VL_ATTR_COLD void VMain___024root__trace_init_sub__TOP__Main__cpucore__EXE__alu__0(VMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_init_sub__TOP__Main__cpucore__EXE__alu__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBus(c+291,"io_alu_op", false,-1, 4,0);
    tracep->declBus(c+382,"io_src1", false,-1, 31,0);
    tracep->declBus(c+383,"io_src2", false,-1, 31,0);
    tracep->declBus(c+384,"io_res", false,-1, 31,0);
    tracep->declBit(c+292,"op_add", false,-1);
    tracep->declBit(c+293,"op_sub", false,-1);
    tracep->declBit(c+294,"op_slt", false,-1);
    tracep->declBit(c+295,"op_sltu", false,-1);
    tracep->declBit(c+296,"op_and", false,-1);
    tracep->declBit(c+297,"op_nor", false,-1);
    tracep->declBit(c+298,"op_or", false,-1);
    tracep->declBit(c+299,"op_xor", false,-1);
    tracep->declBit(c+300,"op_sll", false,-1);
    tracep->declBit(c+301,"op_srl", false,-1);
    tracep->declBit(c+302,"op_sra", false,-1);
    tracep->declBit(c+303,"op_lui", false,-1);
    tracep->declBit(c+304,"op_mul", false,-1);
    tracep->declBit(c+305,"op_mulh", false,-1);
    tracep->declBit(c+306,"op_mulhu", false,-1);
    tracep->declBit(c+307,"op_div", false,-1);
    tracep->declBit(c+308,"op_mod", false,-1);
    tracep->declBit(c+309,"op_divu", false,-1);
    tracep->declBit(c+310,"op_modu", false,-1);
    tracep->declBit(c+311,"add_sub", false,-1);
    tracep->declQuad(c+385,"add_res", false,-1, 32,0);
    tracep->declBit(c+387,"slt_res", false,-1);
    tracep->declBit(c+388,"sltu_res", false,-1);
    tracep->declBus(c+389,"and_res", false,-1, 31,0);
    tracep->declBus(c+390,"or_res", false,-1, 31,0);
    tracep->declBus(c+391,"nor_res", false,-1, 31,0);
    tracep->declBus(c+392,"xor_res", false,-1, 31,0);
    tracep->declQuad(c+393,"sll_res", false,-1, 62,0);
    tracep->declQuad(c+395,"sr", false,-1, 63,0);
    tracep->declQuad(c+397,"sr_res", false,-1, 63,0);
    tracep->declQuad(c+399,"mul_pre", false,-1, 63,0);
    tracep->declBus(c+401,"mul_res", false,-1, 31,0);
    tracep->declBus(c+402,"mulhu_res", false,-1, 31,0);
    tracep->declBus(c+403,"mulh_res", false,-1, 31,0);
    tracep->declBus(c+404,"divu_res", false,-1, 31,0);
    tracep->declBus(c+405,"modu_res", false,-1, 31,0);
    tracep->declBus(c+406,"mod_res", false,-1, 31,0);
    tracep->declBus(c+407,"div_res", false,-1, 31,0);
}

VL_ATTR_COLD void VMain___024root__trace_init_sub__TOP__Main__cpucore__ID__reg___npc_brk__0(VMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_init_sub__TOP__Main__cpucore__ID__reg___npc_brk__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+312,"is_break", false,-1);
}

VL_ATTR_COLD void VMain___024root__trace_init_sub__TOP__Main__cpucore__ID__reg___difftest__0(VMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_init_sub__TOP__Main__cpucore__ID__reg___difftest__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBus(c+74,"rf_0", false,-1, 31,0);
    tracep->declBus(c+502,"rf_1", false,-1, 31,0);
    tracep->declBus(c+503,"rf_2", false,-1, 31,0);
    tracep->declBus(c+504,"rf_3", false,-1, 31,0);
    tracep->declBus(c+505,"rf_4", false,-1, 31,0);
    tracep->declBus(c+506,"rf_5", false,-1, 31,0);
    tracep->declBus(c+507,"rf_6", false,-1, 31,0);
    tracep->declBus(c+508,"rf_7", false,-1, 31,0);
    tracep->declBus(c+509,"rf_8", false,-1, 31,0);
    tracep->declBus(c+510,"rf_9", false,-1, 31,0);
    tracep->declBus(c+511,"rf_10", false,-1, 31,0);
    tracep->declBus(c+512,"rf_11", false,-1, 31,0);
    tracep->declBus(c+513,"rf_12", false,-1, 31,0);
    tracep->declBus(c+514,"rf_13", false,-1, 31,0);
    tracep->declBus(c+515,"rf_14", false,-1, 31,0);
    tracep->declBus(c+516,"rf_15", false,-1, 31,0);
    tracep->declBus(c+517,"rf_16", false,-1, 31,0);
    tracep->declBus(c+518,"rf_17", false,-1, 31,0);
    tracep->declBus(c+519,"rf_18", false,-1, 31,0);
    tracep->declBus(c+520,"rf_19", false,-1, 31,0);
    tracep->declBus(c+521,"rf_20", false,-1, 31,0);
    tracep->declBus(c+522,"rf_21", false,-1, 31,0);
    tracep->declBus(c+523,"rf_22", false,-1, 31,0);
    tracep->declBus(c+524,"rf_23", false,-1, 31,0);
    tracep->declBus(c+525,"rf_24", false,-1, 31,0);
    tracep->declBus(c+526,"rf_25", false,-1, 31,0);
    tracep->declBus(c+527,"rf_26", false,-1, 31,0);
    tracep->declBus(c+528,"rf_27", false,-1, 31,0);
    tracep->declBus(c+529,"rf_28", false,-1, 31,0);
    tracep->declBus(c+530,"rf_29", false,-1, 31,0);
    tracep->declBus(c+531,"rf_30", false,-1, 31,0);
    tracep->declBus(c+532,"rf_31", false,-1, 31,0);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+533+i*1,"regs", true,(i+0), 31,0);
    }
}

VL_ATTR_COLD void VMain___024root__trace_init_sub__TOP__Main__cpucore__ID__reg___inst_exec_once__0(VMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_init_sub__TOP__Main__cpucore__ID__reg___inst_exec_once__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+122,"valid", false,-1);
    tracep->declBus(c+600,"pc", false,-1, 31,0);
    tracep->declBus(c+313,"inst", false,-1, 31,0);
}

VL_ATTR_COLD void VMain___024root__trace_init_top(VMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_init_top\n"); );
    // Body
    VMain___024root__trace_init_sub__TOP__0(vlSelf, tracep);
    tracep->pushNamePrefix("Main ");
    VMain___024root__trace_init_sub__TOP__Main__0(vlSelf, tracep);
    tracep->pushNamePrefix("cpucore ");
    VMain___024root__trace_init_sub__TOP__Main__cpucore__0(vlSelf, tracep);
    tracep->pushNamePrefix("EXE ");
    VMain___024root__trace_init_sub__TOP__Main__cpucore__EXE__0(vlSelf, tracep);
    tracep->pushNamePrefix("alu ");
    VMain___024root__trace_init_sub__TOP__Main__cpucore__EXE__alu__0(vlSelf, tracep);
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("ID ");
    VMain___024root__trace_init_sub__TOP__Main__cpucore__ID__0(vlSelf, tracep);
    tracep->pushNamePrefix("reg_ ");
    VMain___024root__trace_init_sub__TOP__Main__cpucore__ID__reg___0(vlSelf, tracep);
    tracep->pushNamePrefix("difftest ");
    VMain___024root__trace_init_sub__TOP__Main__cpucore__ID__reg___difftest__0(vlSelf, tracep);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("inst_exec_once ");
    VMain___024root__trace_init_sub__TOP__Main__cpucore__ID__reg___inst_exec_once__0(vlSelf, tracep);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("npc_brk ");
    VMain___024root__trace_init_sub__TOP__Main__cpucore__ID__reg___npc_brk__0(vlSelf, tracep);
    tracep->popNamePrefix(3);
    tracep->pushNamePrefix("IF ");
    VMain___024root__trace_init_sub__TOP__Main__cpucore__IF__0(vlSelf, tracep);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("MEM ");
    VMain___024root__trace_init_sub__TOP__Main__cpucore__MEM__0(vlSelf, tracep);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("WB ");
    VMain___024root__trace_init_sub__TOP__Main__cpucore__WB__0(vlSelf, tracep);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("pIF ");
    VMain___024root__trace_init_sub__TOP__Main__cpucore__pIF__0(vlSelf, tracep);
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("dram ");
    VMain___024root__trace_init_sub__TOP__Main__dram__0(vlSelf, tracep);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("iram ");
    VMain___024root__trace_init_sub__TOP__Main__iram__0(vlSelf, tracep);
    tracep->popNamePrefix(2);
}

VL_ATTR_COLD void VMain___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void VMain___024root__trace_chg_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void VMain___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void VMain___024root__trace_register(VMain___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_register\n"); );
    // Body
    tracep->addFullCb(&VMain___024root__trace_full_top_0, vlSelf);
    tracep->addChgCb(&VMain___024root__trace_chg_top_0, vlSelf);
    tracep->addCleanupCb(&VMain___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void VMain___024root__trace_full_sub_0(VMain___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void VMain___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_full_top_0\n"); );
    // Init
    VMain___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<VMain___024root*>(voidSelf);
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    VMain___024root__trace_full_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void VMain___024root__trace_full_sub_0(VMain___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    VMain__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VMain___024root__trace_full_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSymsp->TOP__Main.__PVT__iram_wr));
    bufp->fullIData(oldp+2,(vlSymsp->TOP__Main.__PVT__iram_wdata),32);
    bufp->fullCData(oldp+3,(vlSymsp->TOP__Main.__PVT__iram_wstrb),4);
    bufp->fullBit(oldp+4,(vlSymsp->TOP__Main__iram.__PVT__wr));
    bufp->fullIData(oldp+5,(vlSymsp->TOP__Main__iram.__PVT__wdata),32);
    bufp->fullCData(oldp+6,(vlSymsp->TOP__Main__iram.__PVT__wstrb),4);
    bufp->fullBit(oldp+7,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_io_rdata1_MPORT_en));
    bufp->fullBit(oldp+8,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_io_rdata2_MPORT_en));
    bufp->fullBit(oldp+9,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_1_MPORT_en));
    bufp->fullCData(oldp+10,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_1_MPORT_addr),5);
    bufp->fullBit(oldp+11,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_2_MPORT_en));
    bufp->fullCData(oldp+12,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_2_MPORT_addr),5);
    bufp->fullBit(oldp+13,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_3_MPORT_en));
    bufp->fullCData(oldp+14,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_3_MPORT_addr),5);
    bufp->fullBit(oldp+15,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_4_MPORT_en));
    bufp->fullCData(oldp+16,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_4_MPORT_addr),5);
    bufp->fullBit(oldp+17,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_5_MPORT_en));
    bufp->fullCData(oldp+18,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_5_MPORT_addr),5);
    bufp->fullBit(oldp+19,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_6_MPORT_en));
    bufp->fullCData(oldp+20,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_6_MPORT_addr),5);
    bufp->fullBit(oldp+21,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_7_MPORT_en));
    bufp->fullCData(oldp+22,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_7_MPORT_addr),5);
    bufp->fullBit(oldp+23,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_8_MPORT_en));
    bufp->fullCData(oldp+24,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_8_MPORT_addr),5);
    bufp->fullBit(oldp+25,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_9_MPORT_en));
    bufp->fullCData(oldp+26,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_9_MPORT_addr),5);
    bufp->fullBit(oldp+27,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_10_MPORT_en));
    bufp->fullCData(oldp+28,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_10_MPORT_addr),5);
    bufp->fullBit(oldp+29,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_11_MPORT_en));
    bufp->fullCData(oldp+30,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_11_MPORT_addr),5);
    bufp->fullBit(oldp+31,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_12_MPORT_en));
    bufp->fullCData(oldp+32,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_12_MPORT_addr),5);
    bufp->fullBit(oldp+33,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_13_MPORT_en));
    bufp->fullCData(oldp+34,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_13_MPORT_addr),5);
    bufp->fullBit(oldp+35,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_14_MPORT_en));
    bufp->fullCData(oldp+36,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_14_MPORT_addr),5);
    bufp->fullBit(oldp+37,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_15_MPORT_en));
    bufp->fullCData(oldp+38,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_15_MPORT_addr),5);
    bufp->fullBit(oldp+39,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_16_MPORT_en));
    bufp->fullCData(oldp+40,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_16_MPORT_addr),5);
    bufp->fullBit(oldp+41,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_17_MPORT_en));
    bufp->fullCData(oldp+42,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_17_MPORT_addr),5);
    bufp->fullBit(oldp+43,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_18_MPORT_en));
    bufp->fullCData(oldp+44,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_18_MPORT_addr),5);
    bufp->fullBit(oldp+45,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_19_MPORT_en));
    bufp->fullCData(oldp+46,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_19_MPORT_addr),5);
    bufp->fullBit(oldp+47,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_20_MPORT_en));
    bufp->fullCData(oldp+48,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_20_MPORT_addr),5);
    bufp->fullBit(oldp+49,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_21_MPORT_en));
    bufp->fullCData(oldp+50,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_21_MPORT_addr),5);
    bufp->fullBit(oldp+51,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_22_MPORT_en));
    bufp->fullCData(oldp+52,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_22_MPORT_addr),5);
    bufp->fullBit(oldp+53,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_23_MPORT_en));
    bufp->fullCData(oldp+54,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_23_MPORT_addr),5);
    bufp->fullBit(oldp+55,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_24_MPORT_en));
    bufp->fullCData(oldp+56,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_24_MPORT_addr),5);
    bufp->fullBit(oldp+57,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_25_MPORT_en));
    bufp->fullCData(oldp+58,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_25_MPORT_addr),5);
    bufp->fullBit(oldp+59,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_26_MPORT_en));
    bufp->fullCData(oldp+60,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_26_MPORT_addr),5);
    bufp->fullBit(oldp+61,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_27_MPORT_en));
    bufp->fullCData(oldp+62,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_27_MPORT_addr),5);
    bufp->fullBit(oldp+63,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_28_MPORT_en));
    bufp->fullCData(oldp+64,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_28_MPORT_addr),5);
    bufp->fullBit(oldp+65,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_29_MPORT_en));
    bufp->fullCData(oldp+66,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_29_MPORT_addr),5);
    bufp->fullBit(oldp+67,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_30_MPORT_en));
    bufp->fullCData(oldp+68,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_30_MPORT_addr),5);
    bufp->fullBit(oldp+69,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_31_MPORT_en));
    bufp->fullCData(oldp+70,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_31_MPORT_addr),5);
    bufp->fullBit(oldp+71,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_MPORT_mask));
    bufp->fullBit(oldp+72,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_MPORT_en));
    bufp->fullIData(oldp+73,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_0),32);
    bufp->fullIData(oldp+74,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_0),32);
    bufp->fullBit(oldp+75,(vlSymsp->TOP__Main.clock));
    bufp->fullBit(oldp+76,(vlSymsp->TOP__Main.reset));
    bufp->fullBit(oldp+77,(vlSymsp->TOP__Main.__PVT__cpucore_clock));
    bufp->fullBit(oldp+78,(vlSymsp->TOP__Main.__PVT__cpucore_reset));
    bufp->fullBit(oldp+79,(vlSymsp->TOP__Main.__PVT__cpucore_inst_sram_en));
    bufp->fullBit(oldp+80,(vlSymsp->TOP__Main.__PVT__iram_en));
    bufp->fullBit(oldp+81,(vlSymsp->TOP__Main__cpucore.__PVT__clock));
    bufp->fullBit(oldp+82,(vlSymsp->TOP__Main__cpucore.__PVT__reset));
    bufp->fullBit(oldp+83,(vlSymsp->TOP__Main__cpucore.__PVT__inst_sram_en));
    bufp->fullBit(oldp+84,(vlSymsp->TOP__Main__cpucore.__PVT__pIF_clock));
    bufp->fullBit(oldp+85,(vlSymsp->TOP__Main__cpucore.__PVT__pIF_reset));
    bufp->fullBit(oldp+86,(vlSymsp->TOP__Main__cpucore.__PVT__pIF_inst_sram_en));
    bufp->fullBit(oldp+87,(vlSymsp->TOP__Main__cpucore.__PVT__pIF_tofs_valid));
    bufp->fullBit(oldp+88,(vlSymsp->TOP__Main__cpucore.__PVT__IF_tods_valid));
    bufp->fullBit(oldp+89,(vlSymsp->TOP__Main__cpucore.__PVT__IF_fs_valid));
    bufp->fullBit(oldp+90,(vlSymsp->TOP__Main__cpucore.__PVT__ID_clock));
    bufp->fullBit(oldp+91,(vlSymsp->TOP__Main__cpucore.__PVT__ID_toes_valid));
    bufp->fullBit(oldp+92,(vlSymsp->TOP__Main__cpucore.__PVT__ID_ds_valid));
    bufp->fullBit(oldp+93,(vlSymsp->TOP__Main__cpucore.__PVT__ID_torf_valid));
    bufp->fullBit(oldp+94,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_es_valid));
    bufp->fullBit(oldp+95,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_toms_valid));
    bufp->fullBit(oldp+96,(vlSymsp->TOP__Main__cpucore.__PVT__MEM_ms_valid));
    bufp->fullBit(oldp+97,(vlSymsp->TOP__Main__cpucore.__PVT__MEM_tows_valid));
    bufp->fullBit(oldp+98,(vlSymsp->TOP__Main__cpucore.__PVT__WB_ws_valid));
    bufp->fullBit(oldp+99,(vlSymsp->TOP__Main__cpucore.__PVT__WB_torf_valid));
    bufp->fullBit(oldp+100,(vlSymsp->TOP__Main__iram.__PVT__en));
    bufp->fullBit(oldp+101,(vlSymsp->TOP__Main__cpucore__pIF.__PVT__clock));
    bufp->fullBit(oldp+102,(vlSymsp->TOP__Main__cpucore__pIF.__PVT__reset));
    bufp->fullBit(oldp+103,(vlSymsp->TOP__Main__cpucore__pIF.__PVT__inst_sram_en));
    bufp->fullBit(oldp+104,(vlSymsp->TOP__Main__cpucore__pIF.__PVT__tofs_valid));
    bufp->fullBit(oldp+105,(vlSymsp->TOP__Main__cpucore__IF.__PVT__tods_valid));
    bufp->fullBit(oldp+106,(vlSymsp->TOP__Main__cpucore__IF.__PVT__fs_valid));
    bufp->fullBit(oldp+107,(vlSymsp->TOP__Main__cpucore__ID.__PVT__clock));
    bufp->fullBit(oldp+108,(vlSymsp->TOP__Main__cpucore__ID.__PVT__toes_valid));
    bufp->fullBit(oldp+109,(vlSymsp->TOP__Main__cpucore__ID.__PVT__ds_valid));
    bufp->fullBit(oldp+110,(vlSymsp->TOP__Main__cpucore__ID.__PVT__torf_valid));
    bufp->fullBit(oldp+111,(vlSymsp->TOP__Main__cpucore__ID.__PVT__reg___05Fclock));
    bufp->fullBit(oldp+112,(vlSymsp->TOP__Main__cpucore__ID.__PVT__reg___05Fio_valid));
    bufp->fullBit(oldp+113,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__es_valid));
    bufp->fullBit(oldp+114,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__toms_valid));
    bufp->fullBit(oldp+115,(vlSymsp->TOP__Main__cpucore__MEM.__PVT__ms_valid));
    bufp->fullBit(oldp+116,(vlSymsp->TOP__Main__cpucore__MEM.__PVT__tows_valid));
    bufp->fullBit(oldp+117,(vlSymsp->TOP__Main__cpucore__WB.__PVT__ws_valid));
    bufp->fullBit(oldp+118,(vlSymsp->TOP__Main__cpucore__WB.__PVT__torf_valid));
    bufp->fullBit(oldp+119,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__clock));
    bufp->fullBit(oldp+120,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__io_valid));
    bufp->fullBit(oldp+121,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__inst_exec_once_valid));
    bufp->fullBit(oldp+122,(vlSymsp->TOP__Main__cpucore__ID__reg___inst_exec_once.__PVT__valid));
    bufp->fullIData(oldp+123,(vlSymsp->TOP__Main.__PVT__cpucore_inst_sram_rdata),32);
    bufp->fullBit(oldp+124,(vlSymsp->TOP__Main.__PVT__cpucore_data_sram_en));
    bufp->fullBit(oldp+125,(vlSymsp->TOP__Main.__PVT__cpucore_data_sram_wr));
    bufp->fullCData(oldp+126,(vlSymsp->TOP__Main.__PVT__cpucore_data_sram_wstrb),4);
    bufp->fullBit(oldp+127,(vlSymsp->TOP__Main.__PVT__dram_en));
    bufp->fullBit(oldp+128,(vlSymsp->TOP__Main.__PVT__dram_wr));
    bufp->fullCData(oldp+129,(vlSymsp->TOP__Main.__PVT__dram_wstrb),4);
    bufp->fullIData(oldp+130,(vlSymsp->TOP__Main.__PVT__iram_rdata),32);
    bufp->fullBit(oldp+131,(vlSymsp->TOP__Main__dram.__PVT__en));
    bufp->fullBit(oldp+132,(vlSymsp->TOP__Main__dram.__PVT__wr));
    bufp->fullCData(oldp+133,(vlSymsp->TOP__Main__dram.__PVT__wstrb),4);
    bufp->fullIData(oldp+134,(vlSymsp->TOP__Main__cpucore.__PVT__inst_sram_rdata),32);
    bufp->fullBit(oldp+135,(vlSymsp->TOP__Main__cpucore.__PVT__data_sram_en));
    bufp->fullBit(oldp+136,(vlSymsp->TOP__Main__cpucore.__PVT__data_sram_wr));
    bufp->fullCData(oldp+137,(vlSymsp->TOP__Main__cpucore.__PVT__data_sram_wstrb),4);
    bufp->fullIData(oldp+138,(vlSymsp->TOP__Main__cpucore.__PVT__IF_tods_bits_inst),32);
    bufp->fullIData(oldp+139,(vlSymsp->TOP__Main__cpucore.__PVT__IF_inst_sram_rdata),32);
    bufp->fullCData(oldp+140,(vlSymsp->TOP__Main__cpucore.__PVT__ID_toes_bits_alu_op),5);
    bufp->fullCData(oldp+141,(vlSymsp->TOP__Main__cpucore.__PVT__ID_toes_bits_rf_waddr),5);
    bufp->fullCData(oldp+142,(vlSymsp->TOP__Main__cpucore.__PVT__ID_toes_bits_mem_we),2);
    bufp->fullCData(oldp+143,(vlSymsp->TOP__Main__cpucore.__PVT__ID_toes_bits_inst_name),5);
    bufp->fullBit(oldp+144,(vlSymsp->TOP__Main__cpucore.__PVT__ID_toes_bits_is_break));
    bufp->fullIData(oldp+145,(vlSymsp->TOP__Main__cpucore.__PVT__ID_toes_bits_inst),32);
    bufp->fullIData(oldp+146,(vlSymsp->TOP__Main__cpucore.__PVT__ID_ds_bits_inst),32);
    bufp->fullCData(oldp+147,(vlSymsp->TOP__Main__cpucore.__PVT__ID_torf_rf_waddr),5);
    bufp->fullBit(oldp+148,(vlSymsp->TOP__Main__cpucore.__PVT__ID_torf_is_break));
    bufp->fullIData(oldp+149,(vlSymsp->TOP__Main__cpucore.__PVT__ID_torf_inst),32);
    bufp->fullCData(oldp+150,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_es_bits_alu_op),5);
    bufp->fullCData(oldp+151,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_es_bits_rf_waddr),5);
    bufp->fullCData(oldp+152,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_es_bits_mem_we),2);
    bufp->fullCData(oldp+153,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_es_bits_inst_name),5);
    bufp->fullBit(oldp+154,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_es_bits_is_break));
    bufp->fullIData(oldp+155,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_es_bits_inst),32);
    bufp->fullCData(oldp+156,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_toms_bits_inst_name),5);
    bufp->fullBit(oldp+157,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_toms_bits_res_from_mem));
    bufp->fullCData(oldp+158,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_toms_bits_rf_waddr),5);
    bufp->fullBit(oldp+159,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_toms_bits_is_break));
    bufp->fullIData(oldp+160,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_toms_bits_inst),32);
    bufp->fullBit(oldp+161,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_data_sram_en));
    bufp->fullBit(oldp+162,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_data_sram_wr));
    bufp->fullCData(oldp+163,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_data_sram_wstrb),4);
    bufp->fullCData(oldp+164,(vlSymsp->TOP__Main__cpucore.__PVT__MEM_ms_bits_inst_name),5);
    bufp->fullBit(oldp+165,(vlSymsp->TOP__Main__cpucore.__PVT__MEM_ms_bits_res_from_mem));
    bufp->fullCData(oldp+166,(vlSymsp->TOP__Main__cpucore.__PVT__MEM_ms_bits_rf_waddr),5);
    bufp->fullBit(oldp+167,(vlSymsp->TOP__Main__cpucore.__PVT__MEM_ms_bits_is_break));
    bufp->fullIData(oldp+168,(vlSymsp->TOP__Main__cpucore.__PVT__MEM_ms_bits_inst),32);
    bufp->fullCData(oldp+169,(vlSymsp->TOP__Main__cpucore.__PVT__MEM_tows_bits_rf_waddr),5);
    bufp->fullBit(oldp+170,(vlSymsp->TOP__Main__cpucore.__PVT__MEM_tows_bits_is_break));
    bufp->fullIData(oldp+171,(vlSymsp->TOP__Main__cpucore.__PVT__MEM_tows_bits_inst),32);
    bufp->fullCData(oldp+172,(vlSymsp->TOP__Main__cpucore.__PVT__WB_ws_bits_rf_waddr),5);
    bufp->fullBit(oldp+173,(vlSymsp->TOP__Main__cpucore.__PVT__WB_ws_bits_is_break));
    bufp->fullIData(oldp+174,(vlSymsp->TOP__Main__cpucore.__PVT__WB_ws_bits_inst),32);
    bufp->fullCData(oldp+175,(vlSymsp->TOP__Main__cpucore.__PVT__WB_torf_rf_waddr),5);
    bufp->fullBit(oldp+176,(vlSymsp->TOP__Main__cpucore.__PVT__WB_torf_is_break));
    bufp->fullIData(oldp+177,(vlSymsp->TOP__Main__cpucore.__PVT__WB_torf_inst),32);
    bufp->fullIData(oldp+178,(vlSymsp->TOP__Main__iram.__PVT__rdata),32);
    bufp->fullIData(oldp+179,(vlSymsp->TOP__Main__cpucore__IF.__PVT__tods_bits_inst),32);
    bufp->fullIData(oldp+180,(vlSymsp->TOP__Main__cpucore__IF.__PVT__inst_sram_rdata),32);
    bufp->fullCData(oldp+181,(vlSymsp->TOP__Main__cpucore__ID.__PVT__toes_bits_alu_op),5);
    bufp->fullCData(oldp+182,(vlSymsp->TOP__Main__cpucore__ID.__PVT__toes_bits_rf_waddr),5);
    bufp->fullCData(oldp+183,(vlSymsp->TOP__Main__cpucore__ID.__PVT__toes_bits_mem_we),2);
    bufp->fullCData(oldp+184,(vlSymsp->TOP__Main__cpucore__ID.__PVT__toes_bits_inst_name),5);
    bufp->fullBit(oldp+185,(vlSymsp->TOP__Main__cpucore__ID.__PVT__toes_bits_is_break));
    bufp->fullIData(oldp+186,(vlSymsp->TOP__Main__cpucore__ID.__PVT__toes_bits_inst),32);
    bufp->fullIData(oldp+187,(vlSymsp->TOP__Main__cpucore__ID.__PVT__ds_bits_inst),32);
    bufp->fullCData(oldp+188,(vlSymsp->TOP__Main__cpucore__ID.__PVT__torf_rf_waddr),5);
    bufp->fullBit(oldp+189,(vlSymsp->TOP__Main__cpucore__ID.__PVT__torf_is_break));
    bufp->fullIData(oldp+190,(vlSymsp->TOP__Main__cpucore__ID.__PVT__torf_inst),32);
    bufp->fullCData(oldp+191,(vlSymsp->TOP__Main__cpucore__ID.__PVT__reg___05Fio_raddr1),5);
    bufp->fullCData(oldp+192,(vlSymsp->TOP__Main__cpucore__ID.__PVT__reg___05Fio_raddr2),5);
    bufp->fullCData(oldp+193,(vlSymsp->TOP__Main__cpucore__ID.__PVT__reg___05Fio_waddr),5);
    bufp->fullBit(oldp+194,(vlSymsp->TOP__Main__cpucore__ID.__PVT__reg___05Fio_is_break));
    bufp->fullIData(oldp+195,(vlSymsp->TOP__Main__cpucore__ID.__PVT__reg___05Fio_inst),32);
    bufp->fullCData(oldp+196,(vlSymsp->TOP__Main__cpucore__ID.__PVT__rd),5);
    bufp->fullCData(oldp+197,(vlSymsp->TOP__Main__cpucore__ID.__PVT__rk),5);
    bufp->fullSData(oldp+198,(vlSymsp->TOP__Main__cpucore__ID.__PVT__imm12u),12);
    bufp->fullIData(oldp+199,(vlSymsp->TOP__Main__cpucore__ID.__PVT__imm12),32);
    bufp->fullIData(oldp+200,(vlSymsp->TOP__Main__cpucore__ID.__PVT__imm20),32);
    bufp->fullIData(oldp+201,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_invInputs),32);
    bufp->fullBit(oldp+202,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_0));
    bufp->fullBit(oldp+203,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_1));
    bufp->fullBit(oldp+204,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_2));
    bufp->fullBit(oldp+205,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_3));
    bufp->fullBit(oldp+206,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_4));
    bufp->fullBit(oldp+207,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_5));
    bufp->fullBit(oldp+208,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_6));
    bufp->fullBit(oldp+209,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_7));
    bufp->fullBit(oldp+210,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_8));
    bufp->fullBit(oldp+211,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_9));
    bufp->fullBit(oldp+212,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_10));
    bufp->fullBit(oldp+213,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_11));
    bufp->fullBit(oldp+214,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_12));
    bufp->fullBit(oldp+215,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_13));
    bufp->fullBit(oldp+216,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_14));
    bufp->fullCData(oldp+217,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_lo),7);
    bufp->fullBit(oldp+218,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_3_1));
    bufp->fullCData(oldp+219,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_lo_1),8);
    bufp->fullBit(oldp+220,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_2_2));
    bufp->fullBit(oldp+221,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_1_4));
    bufp->fullBit(oldp+222,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_1_5));
    bufp->fullBit(oldp+223,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_0_7));
    bufp->fullBit(oldp+224,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_2_8));
    bufp->fullBit(oldp+225,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_3_18));
    bufp->fullBit(oldp+226,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_3_23));
    bufp->fullBit(oldp+227,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_4_23));
    bufp->fullBit(oldp+228,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_6_27));
    bufp->fullBit(oldp+229,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_2_31));
    bufp->fullBit(oldp+230,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_1_35));
    bufp->fullBit(oldp+231,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_1_36));
    bufp->fullBit(oldp+232,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_1_41));
    bufp->fullBit(oldp+233,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_2_41));
    bufp->fullBit(oldp+234,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_2_43));
    bufp->fullBit(oldp+235,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_5_44));
    bufp->fullBit(oldp+236,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_andMatrixInput_3_57));
    bufp->fullCData(oldp+237,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_orMatrixOutputs_lo),8);
    bufp->fullCData(oldp+238,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_orMatrixOutputs_hi_5),3);
    bufp->fullCData(oldp+239,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_orMatrixOutputs_lo_6),7);
    bufp->fullCData(oldp+240,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_orMatrixOutputs_lo_9),8);
    bufp->fullCData(oldp+241,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_orMatrixOutputs_lo_10),6);
    bufp->fullCData(oldp+242,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_orMatrixOutputs_lo_13),8);
    bufp->fullIData(oldp+243,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_orMatrixOutputs),17);
    bufp->fullCData(oldp+244,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_invMatrixOutputs_lo),8);
    bufp->fullIData(oldp+245,(vlSymsp->TOP__Main__cpucore__ID.__PVT__decode_res_invMatrixOutputs),17);
    bufp->fullCData(oldp+246,(vlSymsp->TOP__Main__cpucore__ID.__PVT__inst_type),4);
    bufp->fullCData(oldp+247,(vlSymsp->TOP__Main__cpucore__ID.__PVT__mem_we),2);
    bufp->fullCData(oldp+248,(vlSymsp->TOP__Main__cpucore__ID.__PVT__inst_name),5);
    bufp->fullIData(oldp+249,(vlSymsp->TOP__Main__cpucore__ID.__PVT__imm),32);
    bufp->fullBit(oldp+250,(vlSymsp->TOP__Main__cpucore__ID.__PVT__rk_or_rd));
    bufp->fullBit(oldp+251,(vlSymsp->TOP__Main__cpucore__ID.__PVT__src1_is_pc));
    bufp->fullCData(oldp+252,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__es_bits_alu_op),5);
    bufp->fullCData(oldp+253,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__es_bits_rf_waddr),5);
    bufp->fullCData(oldp+254,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__es_bits_mem_we),2);
    bufp->fullCData(oldp+255,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__es_bits_inst_name),5);
    bufp->fullBit(oldp+256,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__es_bits_is_break));
    bufp->fullIData(oldp+257,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__es_bits_inst),32);
    bufp->fullCData(oldp+258,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__toms_bits_inst_name),5);
    bufp->fullBit(oldp+259,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__toms_bits_res_from_mem));
    bufp->fullCData(oldp+260,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__toms_bits_rf_waddr),5);
    bufp->fullBit(oldp+261,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__toms_bits_is_break));
    bufp->fullIData(oldp+262,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__toms_bits_inst),32);
    bufp->fullBit(oldp+263,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__data_sram_en));
    bufp->fullBit(oldp+264,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__data_sram_wr));
    bufp->fullCData(oldp+265,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__data_sram_wstrb),4);
    bufp->fullCData(oldp+266,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__alu_io_alu_op),5);
    bufp->fullCData(oldp+267,(vlSymsp->TOP__Main__cpucore__MEM.__PVT__ms_bits_inst_name),5);
    bufp->fullBit(oldp+268,(vlSymsp->TOP__Main__cpucore__MEM.__PVT__ms_bits_res_from_mem));
    bufp->fullCData(oldp+269,(vlSymsp->TOP__Main__cpucore__MEM.__PVT__ms_bits_rf_waddr),5);
    bufp->fullBit(oldp+270,(vlSymsp->TOP__Main__cpucore__MEM.__PVT__ms_bits_is_break));
    bufp->fullIData(oldp+271,(vlSymsp->TOP__Main__cpucore__MEM.__PVT__ms_bits_inst),32);
    bufp->fullCData(oldp+272,(vlSymsp->TOP__Main__cpucore__MEM.__PVT__tows_bits_rf_waddr),5);
    bufp->fullBit(oldp+273,(vlSymsp->TOP__Main__cpucore__MEM.__PVT__tows_bits_is_break));
    bufp->fullIData(oldp+274,(vlSymsp->TOP__Main__cpucore__MEM.__PVT__tows_bits_inst),32);
    bufp->fullCData(oldp+275,(vlSymsp->TOP__Main__cpucore__WB.__PVT__ws_bits_rf_waddr),5);
    bufp->fullBit(oldp+276,(vlSymsp->TOP__Main__cpucore__WB.__PVT__ws_bits_is_break));
    bufp->fullIData(oldp+277,(vlSymsp->TOP__Main__cpucore__WB.__PVT__ws_bits_inst),32);
    bufp->fullCData(oldp+278,(vlSymsp->TOP__Main__cpucore__WB.__PVT__torf_rf_waddr),5);
    bufp->fullBit(oldp+279,(vlSymsp->TOP__Main__cpucore__WB.__PVT__torf_is_break));
    bufp->fullIData(oldp+280,(vlSymsp->TOP__Main__cpucore__WB.__PVT__torf_inst),32);
    bufp->fullCData(oldp+281,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__io_raddr1),5);
    bufp->fullCData(oldp+282,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__io_raddr2),5);
    bufp->fullCData(oldp+283,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__io_waddr),5);
    bufp->fullBit(oldp+284,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__io_is_break));
    bufp->fullIData(oldp+285,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__io_inst),32);
    bufp->fullCData(oldp+286,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_io_rdata1_MPORT_addr),5);
    bufp->fullCData(oldp+287,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_io_rdata2_MPORT_addr),5);
    bufp->fullCData(oldp+288,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_MPORT_addr),5);
    bufp->fullBit(oldp+289,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__npc_brk_is_break));
    bufp->fullIData(oldp+290,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__inst_exec_once_inst),32);
    bufp->fullCData(oldp+291,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__io_alu_op),5);
    bufp->fullBit(oldp+292,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_add));
    bufp->fullBit(oldp+293,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_sub));
    bufp->fullBit(oldp+294,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_slt));
    bufp->fullBit(oldp+295,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_sltu));
    bufp->fullBit(oldp+296,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_and));
    bufp->fullBit(oldp+297,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_nor));
    bufp->fullBit(oldp+298,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_or));
    bufp->fullBit(oldp+299,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_xor));
    bufp->fullBit(oldp+300,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_sll));
    bufp->fullBit(oldp+301,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_srl));
    bufp->fullBit(oldp+302,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_sra));
    bufp->fullBit(oldp+303,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_lui));
    bufp->fullBit(oldp+304,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_mul));
    bufp->fullBit(oldp+305,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_mulh));
    bufp->fullBit(oldp+306,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_mulhu));
    bufp->fullBit(oldp+307,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_div));
    bufp->fullBit(oldp+308,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_mod));
    bufp->fullBit(oldp+309,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_divu));
    bufp->fullBit(oldp+310,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__op_modu));
    bufp->fullBit(oldp+311,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__add_sub));
    bufp->fullBit(oldp+312,(vlSymsp->TOP__Main__cpucore__ID__reg___npc_brk.__PVT__is_break));
    bufp->fullIData(oldp+313,(vlSymsp->TOP__Main__cpucore__ID__reg___inst_exec_once.__PVT__inst),32);
    bufp->fullIData(oldp+314,(vlSymsp->TOP__Main.__PVT__cpucore_data_sram_addr),32);
    bufp->fullIData(oldp+315,(vlSymsp->TOP__Main.__PVT__cpucore_data_sram_wdata),32);
    bufp->fullIData(oldp+316,(vlSymsp->TOP__Main.__PVT__cpucore_data_sram_rdata),32);
    bufp->fullIData(oldp+317,(vlSymsp->TOP__Main.__PVT__dram_addr),32);
    bufp->fullIData(oldp+318,(vlSymsp->TOP__Main.__PVT__dram_wdata),32);
    bufp->fullIData(oldp+319,(vlSymsp->TOP__Main.__PVT__dram_rdata),32);
    bufp->fullIData(oldp+320,(vlSymsp->TOP__Main__dram.__PVT__addr),32);
    bufp->fullIData(oldp+321,(vlSymsp->TOP__Main__dram.__PVT__wdata),32);
    bufp->fullIData(oldp+322,(vlSymsp->TOP__Main__dram.__PVT__rdata),32);
    bufp->fullIData(oldp+323,(vlSymsp->TOP__Main__cpucore.__PVT__data_sram_addr),32);
    bufp->fullIData(oldp+324,(vlSymsp->TOP__Main__cpucore.__PVT__data_sram_wdata),32);
    bufp->fullIData(oldp+325,(vlSymsp->TOP__Main__cpucore.__PVT__data_sram_rdata),32);
    bufp->fullBit(oldp+326,(vlSymsp->TOP__Main__cpucore.__PVT__pIF_br_taken));
    bufp->fullIData(oldp+327,(vlSymsp->TOP__Main__cpucore.__PVT__pIF_br_target),32);
    bufp->fullIData(oldp+328,(vlSymsp->TOP__Main__cpucore.__PVT__ID_toes_bits_alu_src1),32);
    bufp->fullIData(oldp+329,(vlSymsp->TOP__Main__cpucore.__PVT__ID_toes_bits_alu_src2),32);
    bufp->fullIData(oldp+330,(vlSymsp->TOP__Main__cpucore.__PVT__ID_toes_bits_mem_wdata),32);
    bufp->fullIData(oldp+331,(vlSymsp->TOP__Main__cpucore.__PVT__ID_torf_rf_wdata),32);
    bufp->fullBit(oldp+332,(vlSymsp->TOP__Main__cpucore.__PVT__ID_br_taken));
    bufp->fullIData(oldp+333,(vlSymsp->TOP__Main__cpucore.__PVT__ID_br_target),32);
    bufp->fullIData(oldp+334,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_es_bits_alu_src1),32);
    bufp->fullIData(oldp+335,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_es_bits_alu_src2),32);
    bufp->fullIData(oldp+336,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_es_bits_mem_wdata),32);
    bufp->fullIData(oldp+337,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_toms_bits_alu_res),32);
    bufp->fullIData(oldp+338,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_data_sram_addr),32);
    bufp->fullIData(oldp+339,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_data_sram_wdata),32);
    bufp->fullIData(oldp+340,(vlSymsp->TOP__Main__cpucore.__PVT__MEM_ms_bits_alu_res),32);
    bufp->fullIData(oldp+341,(vlSymsp->TOP__Main__cpucore.__PVT__MEM_tows_bits_rf_wdata),32);
    bufp->fullIData(oldp+342,(vlSymsp->TOP__Main__cpucore.__PVT__MEM_data_sram_rdata),32);
    bufp->fullIData(oldp+343,(vlSymsp->TOP__Main__cpucore.__PVT__WB_ws_bits_rf_wdata),32);
    bufp->fullIData(oldp+344,(vlSymsp->TOP__Main__cpucore.__PVT__WB_torf_rf_wdata),32);
    bufp->fullBit(oldp+345,(vlSymsp->TOP__Main__cpucore__pIF.__PVT__br_taken));
    bufp->fullIData(oldp+346,(vlSymsp->TOP__Main__cpucore__pIF.__PVT__br_target),32);
    bufp->fullIData(oldp+347,(vlSymsp->TOP__Main__cpucore__ID.__PVT__toes_bits_alu_src1),32);
    bufp->fullIData(oldp+348,(vlSymsp->TOP__Main__cpucore__ID.__PVT__toes_bits_alu_src2),32);
    bufp->fullIData(oldp+349,(vlSymsp->TOP__Main__cpucore__ID.__PVT__toes_bits_mem_wdata),32);
    bufp->fullIData(oldp+350,(vlSymsp->TOP__Main__cpucore__ID.__PVT__torf_rf_wdata),32);
    bufp->fullBit(oldp+351,(vlSymsp->TOP__Main__cpucore__ID.__PVT__br_taken));
    bufp->fullIData(oldp+352,(vlSymsp->TOP__Main__cpucore__ID.__PVT__br_target),32);
    bufp->fullIData(oldp+353,(vlSymsp->TOP__Main__cpucore__ID.__PVT__reg___05Fio_rdata1),32);
    bufp->fullIData(oldp+354,(vlSymsp->TOP__Main__cpucore__ID.__PVT__reg___05Fio_rdata2),32);
    bufp->fullIData(oldp+355,(vlSymsp->TOP__Main__cpucore__ID.__PVT__reg___05Fio_wdata),32);
    bufp->fullBit(oldp+356,(vlSymsp->TOP__Main__cpucore__ID.__PVT__rj_eq_rd));
    bufp->fullQData(oldp+357,(vlSymsp->TOP__Main__cpucore__ID.__PVT__rj_sub_rd),33);
    bufp->fullBit(oldp+359,(vlSymsp->TOP__Main__cpucore__ID.__PVT__slt_res));
    bufp->fullBit(oldp+360,(vlSymsp->TOP__Main__cpucore__ID.__PVT__sltu_res));
    bufp->fullIData(oldp+361,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__es_bits_alu_src1),32);
    bufp->fullIData(oldp+362,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__es_bits_alu_src2),32);
    bufp->fullIData(oldp+363,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__es_bits_mem_wdata),32);
    bufp->fullIData(oldp+364,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__toms_bits_alu_res),32);
    bufp->fullIData(oldp+365,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__data_sram_addr),32);
    bufp->fullIData(oldp+366,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__data_sram_wdata),32);
    bufp->fullIData(oldp+367,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__alu_io_src1),32);
    bufp->fullIData(oldp+368,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__alu_io_src2),32);
    bufp->fullIData(oldp+369,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__alu_io_res),32);
    bufp->fullIData(oldp+370,(vlSymsp->TOP__Main__cpucore__MEM.__PVT__ms_bits_alu_res),32);
    bufp->fullIData(oldp+371,(vlSymsp->TOP__Main__cpucore__MEM.__PVT__tows_bits_rf_wdata),32);
    bufp->fullIData(oldp+372,(vlSymsp->TOP__Main__cpucore__MEM.__PVT__data_sram_rdata),32);
    bufp->fullIData(oldp+373,(vlSymsp->TOP__Main__cpucore__MEM.__PVT__mem_rdata),32);
    bufp->fullIData(oldp+374,(vlSymsp->TOP__Main__cpucore__WB.__PVT__ws_bits_rf_wdata),32);
    bufp->fullIData(oldp+375,(vlSymsp->TOP__Main__cpucore__WB.__PVT__torf_rf_wdata),32);
    bufp->fullIData(oldp+376,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__io_rdata1),32);
    bufp->fullIData(oldp+377,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__io_rdata2),32);
    bufp->fullIData(oldp+378,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__io_wdata),32);
    bufp->fullIData(oldp+379,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_io_rdata1_MPORT_data),32);
    bufp->fullIData(oldp+380,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_io_rdata2_MPORT_data),32);
    bufp->fullIData(oldp+381,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_MPORT_data),32);
    bufp->fullIData(oldp+382,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__io_src1),32);
    bufp->fullIData(oldp+383,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__io_src2),32);
    bufp->fullIData(oldp+384,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__io_res),32);
    bufp->fullQData(oldp+385,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__add_res),33);
    bufp->fullBit(oldp+387,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__slt_res));
    bufp->fullBit(oldp+388,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__sltu_res));
    bufp->fullIData(oldp+389,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__and_res),32);
    bufp->fullIData(oldp+390,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__or_res),32);
    bufp->fullIData(oldp+391,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__nor_res),32);
    bufp->fullIData(oldp+392,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__xor_res),32);
    bufp->fullQData(oldp+393,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__sll_res),63);
    bufp->fullQData(oldp+395,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__sr),64);
    bufp->fullQData(oldp+397,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__sr_res),64);
    bufp->fullQData(oldp+399,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__mul_pre),64);
    bufp->fullIData(oldp+401,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__mul_res),32);
    bufp->fullIData(oldp+402,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__mulhu_res),32);
    bufp->fullIData(oldp+403,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__mulh_res),32);
    bufp->fullIData(oldp+404,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__divu_res),32);
    bufp->fullIData(oldp+405,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__modu_res),32);
    bufp->fullIData(oldp+406,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__mod_res),32);
    bufp->fullIData(oldp+407,(vlSymsp->TOP__Main__cpucore__EXE__alu.__PVT__div_res),32);
    bufp->fullIData(oldp+408,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[0]),32);
    bufp->fullIData(oldp+409,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[1]),32);
    bufp->fullIData(oldp+410,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[2]),32);
    bufp->fullIData(oldp+411,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[3]),32);
    bufp->fullIData(oldp+412,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[4]),32);
    bufp->fullIData(oldp+413,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[5]),32);
    bufp->fullIData(oldp+414,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[6]),32);
    bufp->fullIData(oldp+415,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[7]),32);
    bufp->fullIData(oldp+416,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[8]),32);
    bufp->fullIData(oldp+417,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[9]),32);
    bufp->fullIData(oldp+418,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[10]),32);
    bufp->fullIData(oldp+419,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[11]),32);
    bufp->fullIData(oldp+420,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[12]),32);
    bufp->fullIData(oldp+421,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[13]),32);
    bufp->fullIData(oldp+422,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[14]),32);
    bufp->fullIData(oldp+423,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[15]),32);
    bufp->fullIData(oldp+424,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[16]),32);
    bufp->fullIData(oldp+425,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[17]),32);
    bufp->fullIData(oldp+426,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[18]),32);
    bufp->fullIData(oldp+427,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[19]),32);
    bufp->fullIData(oldp+428,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[20]),32);
    bufp->fullIData(oldp+429,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[21]),32);
    bufp->fullIData(oldp+430,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[22]),32);
    bufp->fullIData(oldp+431,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[23]),32);
    bufp->fullIData(oldp+432,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[24]),32);
    bufp->fullIData(oldp+433,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[25]),32);
    bufp->fullIData(oldp+434,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[26]),32);
    bufp->fullIData(oldp+435,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[27]),32);
    bufp->fullIData(oldp+436,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[28]),32);
    bufp->fullIData(oldp+437,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[29]),32);
    bufp->fullIData(oldp+438,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[30]),32);
    bufp->fullIData(oldp+439,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf[31]),32);
    bufp->fullIData(oldp+440,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_1_MPORT_data),32);
    bufp->fullIData(oldp+441,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_2_MPORT_data),32);
    bufp->fullIData(oldp+442,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_3_MPORT_data),32);
    bufp->fullIData(oldp+443,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_4_MPORT_data),32);
    bufp->fullIData(oldp+444,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_5_MPORT_data),32);
    bufp->fullIData(oldp+445,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_6_MPORT_data),32);
    bufp->fullIData(oldp+446,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_7_MPORT_data),32);
    bufp->fullIData(oldp+447,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_8_MPORT_data),32);
    bufp->fullIData(oldp+448,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_9_MPORT_data),32);
    bufp->fullIData(oldp+449,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_10_MPORT_data),32);
    bufp->fullIData(oldp+450,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_11_MPORT_data),32);
    bufp->fullIData(oldp+451,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_12_MPORT_data),32);
    bufp->fullIData(oldp+452,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_13_MPORT_data),32);
    bufp->fullIData(oldp+453,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_14_MPORT_data),32);
    bufp->fullIData(oldp+454,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_15_MPORT_data),32);
    bufp->fullIData(oldp+455,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_16_MPORT_data),32);
    bufp->fullIData(oldp+456,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_17_MPORT_data),32);
    bufp->fullIData(oldp+457,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_18_MPORT_data),32);
    bufp->fullIData(oldp+458,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_19_MPORT_data),32);
    bufp->fullIData(oldp+459,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_20_MPORT_data),32);
    bufp->fullIData(oldp+460,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_21_MPORT_data),32);
    bufp->fullIData(oldp+461,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_22_MPORT_data),32);
    bufp->fullIData(oldp+462,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_23_MPORT_data),32);
    bufp->fullIData(oldp+463,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_24_MPORT_data),32);
    bufp->fullIData(oldp+464,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_25_MPORT_data),32);
    bufp->fullIData(oldp+465,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_26_MPORT_data),32);
    bufp->fullIData(oldp+466,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_27_MPORT_data),32);
    bufp->fullIData(oldp+467,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_28_MPORT_data),32);
    bufp->fullIData(oldp+468,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_29_MPORT_data),32);
    bufp->fullIData(oldp+469,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_30_MPORT_data),32);
    bufp->fullIData(oldp+470,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__rf_difftest_io_rf_31_MPORT_data),32);
    bufp->fullIData(oldp+471,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_1),32);
    bufp->fullIData(oldp+472,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_2),32);
    bufp->fullIData(oldp+473,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_3),32);
    bufp->fullIData(oldp+474,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_4),32);
    bufp->fullIData(oldp+475,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_5),32);
    bufp->fullIData(oldp+476,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_6),32);
    bufp->fullIData(oldp+477,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_7),32);
    bufp->fullIData(oldp+478,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_8),32);
    bufp->fullIData(oldp+479,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_9),32);
    bufp->fullIData(oldp+480,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_10),32);
    bufp->fullIData(oldp+481,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_11),32);
    bufp->fullIData(oldp+482,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_12),32);
    bufp->fullIData(oldp+483,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_13),32);
    bufp->fullIData(oldp+484,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_14),32);
    bufp->fullIData(oldp+485,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_15),32);
    bufp->fullIData(oldp+486,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_16),32);
    bufp->fullIData(oldp+487,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_17),32);
    bufp->fullIData(oldp+488,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_18),32);
    bufp->fullIData(oldp+489,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_19),32);
    bufp->fullIData(oldp+490,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_20),32);
    bufp->fullIData(oldp+491,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_21),32);
    bufp->fullIData(oldp+492,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_22),32);
    bufp->fullIData(oldp+493,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_23),32);
    bufp->fullIData(oldp+494,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_24),32);
    bufp->fullIData(oldp+495,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_25),32);
    bufp->fullIData(oldp+496,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_26),32);
    bufp->fullIData(oldp+497,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_27),32);
    bufp->fullIData(oldp+498,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_28),32);
    bufp->fullIData(oldp+499,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_29),32);
    bufp->fullIData(oldp+500,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_30),32);
    bufp->fullIData(oldp+501,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__difftest_rf_31),32);
    bufp->fullIData(oldp+502,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_1),32);
    bufp->fullIData(oldp+503,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_2),32);
    bufp->fullIData(oldp+504,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_3),32);
    bufp->fullIData(oldp+505,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_4),32);
    bufp->fullIData(oldp+506,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_5),32);
    bufp->fullIData(oldp+507,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_6),32);
    bufp->fullIData(oldp+508,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_7),32);
    bufp->fullIData(oldp+509,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_8),32);
    bufp->fullIData(oldp+510,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_9),32);
    bufp->fullIData(oldp+511,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_10),32);
    bufp->fullIData(oldp+512,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_11),32);
    bufp->fullIData(oldp+513,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_12),32);
    bufp->fullIData(oldp+514,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_13),32);
    bufp->fullIData(oldp+515,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_14),32);
    bufp->fullIData(oldp+516,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_15),32);
    bufp->fullIData(oldp+517,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_16),32);
    bufp->fullIData(oldp+518,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_17),32);
    bufp->fullIData(oldp+519,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_18),32);
    bufp->fullIData(oldp+520,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_19),32);
    bufp->fullIData(oldp+521,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_20),32);
    bufp->fullIData(oldp+522,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_21),32);
    bufp->fullIData(oldp+523,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_22),32);
    bufp->fullIData(oldp+524,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_23),32);
    bufp->fullIData(oldp+525,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_24),32);
    bufp->fullIData(oldp+526,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_25),32);
    bufp->fullIData(oldp+527,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_26),32);
    bufp->fullIData(oldp+528,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_27),32);
    bufp->fullIData(oldp+529,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_28),32);
    bufp->fullIData(oldp+530,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_29),32);
    bufp->fullIData(oldp+531,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_30),32);
    bufp->fullIData(oldp+532,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__rf_31),32);
    bufp->fullIData(oldp+533,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[0]),32);
    bufp->fullIData(oldp+534,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[1]),32);
    bufp->fullIData(oldp+535,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[2]),32);
    bufp->fullIData(oldp+536,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[3]),32);
    bufp->fullIData(oldp+537,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[4]),32);
    bufp->fullIData(oldp+538,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[5]),32);
    bufp->fullIData(oldp+539,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[6]),32);
    bufp->fullIData(oldp+540,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[7]),32);
    bufp->fullIData(oldp+541,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[8]),32);
    bufp->fullIData(oldp+542,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[9]),32);
    bufp->fullIData(oldp+543,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[10]),32);
    bufp->fullIData(oldp+544,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[11]),32);
    bufp->fullIData(oldp+545,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[12]),32);
    bufp->fullIData(oldp+546,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[13]),32);
    bufp->fullIData(oldp+547,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[14]),32);
    bufp->fullIData(oldp+548,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[15]),32);
    bufp->fullIData(oldp+549,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[16]),32);
    bufp->fullIData(oldp+550,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[17]),32);
    bufp->fullIData(oldp+551,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[18]),32);
    bufp->fullIData(oldp+552,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[19]),32);
    bufp->fullIData(oldp+553,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[20]),32);
    bufp->fullIData(oldp+554,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[21]),32);
    bufp->fullIData(oldp+555,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[22]),32);
    bufp->fullIData(oldp+556,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[23]),32);
    bufp->fullIData(oldp+557,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[24]),32);
    bufp->fullIData(oldp+558,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[25]),32);
    bufp->fullIData(oldp+559,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[26]),32);
    bufp->fullIData(oldp+560,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[27]),32);
    bufp->fullIData(oldp+561,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[28]),32);
    bufp->fullIData(oldp+562,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[29]),32);
    bufp->fullIData(oldp+563,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[30]),32);
    bufp->fullIData(oldp+564,(vlSymsp->TOP__Main__cpucore__ID__reg___difftest.__PVT__regs[31]),32);
    bufp->fullIData(oldp+565,(vlSymsp->TOP__Main.__PVT__cpucore_inst_sram_addr),32);
    bufp->fullIData(oldp+566,(vlSymsp->TOP__Main.__PVT__iram_addr),32);
    bufp->fullIData(oldp+567,(vlSymsp->TOP__Main__cpucore.__PVT__inst_sram_addr),32);
    bufp->fullIData(oldp+568,(vlSymsp->TOP__Main__cpucore.__PVT__pIF_inst_sram_addr),32);
    bufp->fullIData(oldp+569,(vlSymsp->TOP__Main__cpucore.__PVT__pIF_tofs_bits_pc),32);
    bufp->fullIData(oldp+570,(vlSymsp->TOP__Main__cpucore.__PVT__IF_tods_bits_pc),32);
    bufp->fullIData(oldp+571,(vlSymsp->TOP__Main__cpucore.__PVT__IF_fs_bits_pc),32);
    bufp->fullIData(oldp+572,(vlSymsp->TOP__Main__cpucore.__PVT__ID_toes_bits_pc),32);
    bufp->fullIData(oldp+573,(vlSymsp->TOP__Main__cpucore.__PVT__ID_ds_bits_pc),32);
    bufp->fullIData(oldp+574,(vlSymsp->TOP__Main__cpucore.__PVT__ID_torf_pc),32);
    bufp->fullIData(oldp+575,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_es_bits_pc),32);
    bufp->fullIData(oldp+576,(vlSymsp->TOP__Main__cpucore.__PVT__EXE_toms_bits_pc),32);
    bufp->fullIData(oldp+577,(vlSymsp->TOP__Main__cpucore.__PVT__MEM_ms_bits_pc),32);
    bufp->fullIData(oldp+578,(vlSymsp->TOP__Main__cpucore.__PVT__MEM_tows_bits_pc),32);
    bufp->fullIData(oldp+579,(vlSymsp->TOP__Main__cpucore.__PVT__WB_ws_bits_pc),32);
    bufp->fullIData(oldp+580,(vlSymsp->TOP__Main__cpucore.__PVT__WB_torf_pc),32);
    bufp->fullIData(oldp+581,(vlSymsp->TOP__Main__iram.__PVT__addr),32);
    bufp->fullIData(oldp+582,(vlSymsp->TOP__Main__cpucore__pIF.__PVT__inst_sram_addr),32);
    bufp->fullIData(oldp+583,(vlSymsp->TOP__Main__cpucore__pIF.__PVT__tofs_bits_pc),32);
    bufp->fullIData(oldp+584,(vlSymsp->TOP__Main__cpucore__pIF.__PVT__pc),32);
    bufp->fullIData(oldp+585,(vlSymsp->TOP__Main__cpucore__pIF.__PVT__snpc),32);
    bufp->fullIData(oldp+586,(vlSymsp->TOP__Main__cpucore__IF.__PVT__tods_bits_pc),32);
    bufp->fullIData(oldp+587,(vlSymsp->TOP__Main__cpucore__IF.__PVT__fs_bits_pc),32);
    bufp->fullIData(oldp+588,(vlSymsp->TOP__Main__cpucore__ID.__PVT__toes_bits_pc),32);
    bufp->fullIData(oldp+589,(vlSymsp->TOP__Main__cpucore__ID.__PVT__ds_bits_pc),32);
    bufp->fullIData(oldp+590,(vlSymsp->TOP__Main__cpucore__ID.__PVT__torf_pc),32);
    bufp->fullIData(oldp+591,(vlSymsp->TOP__Main__cpucore__ID.__PVT__reg___05Fio_rf_pc),32);
    bufp->fullIData(oldp+592,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__es_bits_pc),32);
    bufp->fullIData(oldp+593,(vlSymsp->TOP__Main__cpucore__EXE.__PVT__toms_bits_pc),32);
    bufp->fullIData(oldp+594,(vlSymsp->TOP__Main__cpucore__MEM.__PVT__ms_bits_pc),32);
    bufp->fullIData(oldp+595,(vlSymsp->TOP__Main__cpucore__MEM.__PVT__tows_bits_pc),32);
    bufp->fullIData(oldp+596,(vlSymsp->TOP__Main__cpucore__WB.__PVT__ws_bits_pc),32);
    bufp->fullIData(oldp+597,(vlSymsp->TOP__Main__cpucore__WB.__PVT__torf_pc),32);
    bufp->fullIData(oldp+598,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__io_rf_pc),32);
    bufp->fullIData(oldp+599,(vlSymsp->TOP__Main__cpucore__ID__reg_.__PVT__inst_exec_once_pc),32);
    bufp->fullIData(oldp+600,(vlSymsp->TOP__Main__cpucore__ID__reg___inst_exec_once.__PVT__pc),32);
    bufp->fullBit(oldp+601,(vlSelf->clock));
    bufp->fullBit(oldp+602,(vlSelf->reset));
}
