// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VMain.h for the primary calling header

#ifndef VERILATED_VMAIN___024ROOT_H_
#define VERILATED_VMAIN___024ROOT_H_  // guard

#include "verilated.h"

class VMain__Syms;

class VMain___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        CData/*0:0*/ Main__DOT__cpucore__DOT__pIF_br_taken;
        CData/*0:0*/ Main__DOT__cpucore__DOT__pIF_csr_br_taken;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID_toes_bits_csr_we;
        CData/*0:0*/ Main__DOT__cpucore__DOT__pIF__DOT__inst_sram_en_REG;
        CData/*7:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_84;
        CData/*5:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_88;
        CData/*6:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_90;
        CData/*6:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_92;
        CData/*7:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_94;
        CData/*7:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_96;
        CData/*7:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_98;
        CData/*4:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_118;
        CData/*5:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_120;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_122;
        CData/*4:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_126;
        CData/*4:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_130;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_132;
        CData/*1:0*/ Main__DOT__cpucore__DOT__ID__DOT__decode_res_orMatrixOutputs_lo_lo_hi;
        CData/*7:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_orMatrixOutputs_T_2;
        CData/*7:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_orMatrixOutputs_T_6;
        CData/*7:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_orMatrixOutputs_T_8;
        CData/*2:0*/ Main__DOT__cpucore__DOT__ID__DOT__decode_res_orMatrixOutputs_hi_5;
        CData/*4:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_orMatrixOutputs_T_10;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_orMatrixOutputs_T_20;
        CData/*4:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_orMatrixOutputs_T_22;
        CData/*5:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_orMatrixOutputs_T_28;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT__inst_type;
        CData/*1:0*/ Main__DOT__cpucore__DOT__ID__DOT__mem_we;
        CData/*4:0*/ Main__DOT__cpucore__DOT__ID__DOT__inst_name;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__rj_eq_rd;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__slt_res;
        CData/*5:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_he1db0bdc__0;
        CData/*7:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_hc442db33__0;
        CData/*6:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_hf81c125f__0;
        CData/*7:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_hf55cf174__0;
        CData/*5:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_hdf4b931c__0;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_hea5ce459__0;
        CData/*5:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h8b89584c__0;
        CData/*6:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h2efe7c47__0;
        CData/*7:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h137d715b__0;
        CData/*2:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h1bd59172__0;
        CData/*1:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h2b6f7eb5__0;
        CData/*1:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h360c0578__0;
        CData/*1:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_hd18ef98c__0;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h6d60535a__0;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h8d80ac40__0;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h68e26b49__0;
        CData/*1:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h6def06bc__0;
        CData/*2:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h5554197b__0;
        CData/*4:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h1a7f0360__0;
        CData/*4:0*/ Main__DOT__cpucore__DOT__ID__DOT__reg___DOT__rf_io_rdata2_MPORT_addr;
        CData/*4:0*/ Main__DOT__cpucore__DOT__ID__DOT__reg___DOT__rf_MPORT_addr;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__reg___DOT__inst_exec_once_ex;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1_out_cout;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__g_2;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__p_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__g___05F1;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__g_1;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__p_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__g___05F0;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__g_4;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__p_4;
    };
    struct {
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__g___05F3;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__g_3;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__p_3;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__g___05F2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__c_carry___05F1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__c_carry___05F2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__c_carry___05F3;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__c_carry_1_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__c_carry_1_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__c_carry_2_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__c_carry_2_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__c_carry_3_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__c_carry_3_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__c_carry_4_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT__c_carry_4_2;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT____VdfgTmp_h80eb44dd__0;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT____VdfgTmp_h805c553a__0;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT____VdfgTmp_h800aa055__0;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_0__DOT____VdfgTmp_h80fabba5__0;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__g_2;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__p_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__g___05F1;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__g_1;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__p_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__g___05F0;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__g_4;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__p_4;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__g___05F3;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__g_3;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__p_3;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__g___05F2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__c_carry___05F1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__c_carry___05F2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__c_carry___05F3;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__c_carry_1_0;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__c_carry_1_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__c_carry_1_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__c_carry_2_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__c_carry_2_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__c_carry_3_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__c_carry_3_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__c_carry_4_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__c_carry_4_2;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT__sum_3;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT____VdfgTmp_h80eb44dd__0;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT____VdfgTmp_h805c553a__0;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT____VdfgTmp_h800aa055__0;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___DOT__add_1__DOT____VdfgTmp_h80fabba5__0;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__g_2;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__p_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__g___05F1;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__g_1;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__p_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__g___05F0;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__g_4;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__p_4;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__g___05F3;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__g_3;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__p_3;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__g___05F2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT___c_T_16;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__c_carry___05F2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__c_carry___05F3;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__c_carry_1_2;
    };
    struct {
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__c_carry_2_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__c_carry_2_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__c_carry_3_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__c_carry_3_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__c_carry_4_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_0__DOT__c_carry_4_2;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__g_2;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__p_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__g___05F1;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__g_1;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__p_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__g___05F0;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__g_4;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__p_4;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__g_3;
        CData/*3:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__p_3;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__g___05F2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__c_carry___05F1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__c_carry___05F2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__c_carry___05F3;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__c_carry_1_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__c_carry_1_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__c_carry_2_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__c_carry_2_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__c_carry_3_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__c_carry_3_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__c_carry_4_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___DOT__add_1__DOT__c_carry_4_2;
        CData/*4:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu_io_alu_op;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1_out_cout;
        CData/*3:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__g_2;
        CData/*3:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__p_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__g___05F1;
        CData/*3:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__g_1;
        CData/*3:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__p_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__g___05F0;
        CData/*3:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__g_4;
        CData/*3:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__p_4;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__g___05F3;
        CData/*3:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__g_3;
        CData/*3:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__p_3;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__g___05F2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__c_carry___05F1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__c_carry___05F2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__c_carry___05F3;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__c_carry_1_0;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__c_carry_1_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__c_carry_1_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__c_carry_2_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__c_carry_2_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__c_carry_3_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__c_carry_3_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__c_carry_4_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_0__DOT__c_carry_4_2;
        CData/*3:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__g_2;
        CData/*3:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__p_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__g___05F1;
        CData/*3:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__g_1;
        CData/*3:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__p_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__g___05F0;
        CData/*3:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__g_4;
        CData/*3:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__p_4;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__g___05F3;
        CData/*3:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__g_3;
    };
    struct {
        CData/*3:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__p_3;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__g___05F2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__c_carry___05F1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__c_carry___05F2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__c_carry___05F3;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__c_carry_1_0;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__c_carry_1_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__c_carry_1_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__c_carry_2_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__c_carry_2_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__c_carry_3_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__c_carry_3_2;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__c_carry_4_1;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__c_carry_4_2;
        CData/*3:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___DOT__add_1__DOT__sum_3;
        CData/*0:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT__shift_res_s__DOT___buf_T_3;
        CData/*0:0*/ __Vtrigrprev__TOP__clock;
        CData/*0:0*/ __VactContinue;
        SData/*14:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T;
        SData/*14:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_4;
        SData/*15:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_10;
        SData/*14:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_16;
        SData/*14:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_18;
        SData/*14:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_26;
        SData/*15:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_32;
        SData/*15:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_40;
        SData/*15:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_42;
        SData/*14:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_46;
        SData/*15:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_52;
        SData/*15:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_56;
        SData/*15:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_58;
        SData/*8:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_64;
        SData/*8:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_66;
        SData/*8:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_72;
        SData/*8:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_74;
        SData/*8:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_78;
        SData/*9:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_80;
        SData/*8:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_100;
        SData/*9:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_110;
        SData/*8:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_112;
        SData/*8:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_orMatrixOutputs_T_4;
        SData/*14:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_orMatrixOutputs_T_16;
        SData/*9:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_orMatrixOutputs_T_18;
        SData/*15:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_orMatrixOutputs_T_24;
        SData/*11:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_orMatrixOutputs_T_26;
        SData/*8:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_orMatrixOutputs_T_30;
        SData/*11:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h924e2e84__0;
        SData/*13:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h3ae392be__0;
        SData/*13:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h52afcb45__0;
        SData/*13:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h138f6fae__0;
        SData/*14:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_hf06ea362__0;
        SData/*13:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h3b60932f__0;
        SData/*12:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h2a536b4b__0;
        SData/*14:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_hbb8003c0__0;
        SData/*11:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_hbb50ecb2__0;
        SData/*14:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h095fdd5d__0;
        SData/*11:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_hb79c9193__0;
        SData/*12:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h92bfeef8__0;
        SData/*8:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h06deb864__0;
        SData/*8:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h5a2ad26b__0;
        SData/*9:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h20fcf308__0;
        SData/*12:0*/ Main__DOT__cpucore__DOT__ID__DOT____VdfgTmp_h75ee0a09__0;
        IData/*31:0*/ Main__DOT__dram_rdata;
        IData/*31:0*/ Main__DOT__iram_rdata;
    };
    struct {
        IData/*31:0*/ Main__DOT__cpucore__DOT__pIF_csr_br_pc;
        IData/*31:0*/ Main__DOT__cpucore__DOT__pIF__DOT__pc;
        IData/*31:0*/ Main__DOT__cpucore__DOT__pIF__DOT__snpc;
        IData/*31:0*/ Main__DOT__cpucore__DOT__ID__DOT__reg___05Fio_rdata1;
        IData/*31:0*/ Main__DOT__cpucore__DOT__ID__DOT__reg___05Fio_rdata2;
        IData/*31:0*/ Main__DOT__cpucore__DOT__ID__DOT___rj_sub_rd_adder___05Fin_b;
        IData/*31:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___05Fin_a;
        IData/*31:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___05Fin_b;
        IData/*31:0*/ Main__DOT__cpucore__DOT__ID__DOT__br_target_adder___05Fout_s;
        IData/*31:0*/ Main__DOT__cpucore__DOT__ID__DOT__imm26;
        IData/*31:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_T_86;
        IData/*17:0*/ Main__DOT__cpucore__DOT__ID__DOT___decode_res_orMatrixOutputs_T;
        IData/*31:0*/ Main__DOT__cpucore__DOT__ID__DOT__reg___DOT__rf_io_rdata1_MPORT_data;
        IData/*31:0*/ Main__DOT__cpucore__DOT__ID__DOT__reg___DOT__rf_io_rdata2_MPORT_data;
        IData/*31:0*/ Main__DOT__cpucore__DOT__ID__DOT__reg___DOT__rf_MPORT_data;
        IData/*31:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu_io_src2;
        IData/*31:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___05Fin_a;
        IData/*31:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___add_res_adder___05Fin_b;
        IData/*31:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT__or_res;
        IData/*31:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___io_res_T_13;
        IData/*31:0*/ Main__DOT__cpucore__DOT__csr__DOT__crmd;
        IData/*31:0*/ Main__DOT__cpucore__DOT__csr__DOT__prmd;
        IData/*31:0*/ Main__DOT__cpucore__DOT__csr__DOT__era;
        IData/*31:0*/ Main__DOT__cpucore__DOT__csr__DOT__estat;
        IData/*31:0*/ Main__DOT__cpucore__DOT__csr__DOT__eentry;
        IData/*31:0*/ Main__DOT__cpucore__DOT__csr__DOT___crmd_T;
        IData/*31:0*/ Main__DOT__cpucore__DOT__csr__DOT___crmd_T_2;
        IData/*31:0*/ Main__DOT__cpucore__DOT__csr__DOT___crmd_T_3;
        IData/*31:0*/ Main__DOT__cpucore__DOT__csr__DOT___crmd_T_6;
        IData/*31:0*/ Main__DOT__cpucore__DOT__csr__DOT___crmd_T_8;
        IData/*31:0*/ Main__DOT__cpucore__DOT__csr__DOT___prmd_T_3;
        IData/*31:0*/ Main__DOT__cpucore__DOT__csr__DOT___prmd_T_6;
        IData/*31:0*/ Main__DOT__cpucore__DOT__csr__DOT___estat_T_3;
        IData/*31:0*/ Main__DOT__cpucore__DOT__csr__DOT___estat_T_5;
        IData/*31:0*/ Main__DOT__cpucore__DOT__csr__DOT___era_T_3;
        IData/*31:0*/ Main__DOT__cpucore__DOT__csr__DOT___eentry_T_3;
        IData/*31:0*/ __Vtask_Main__DOT__dram__DOT__vaddr_write__6__rdata;
        IData/*31:0*/ __Vtask_Main__DOT__dram__DOT__vaddr_read__7__rdata;
        IData/*31:0*/ __Vtask_Main__DOT__iram__DOT__vaddr_fetch__8__rdata;
        IData/*31:0*/ __VstlIterCount;
        IData/*31:0*/ __VicoIterCount;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT__mul_pre;
        QData/*32:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT___io_res_T_18;
        QData/*63:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT__shift_res_s__DOT__buf_;
        QData/*63:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT__shift_res_s__DOT__select_1;
        QData/*63:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT__shift_res_s__DOT__select_2;
        QData/*63:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT__shift_res_s__DOT__select_3;
        QData/*63:0*/ Main__DOT__cpucore__DOT__EXE__DOT__alu__DOT__shift_res_s__DOT__select_4;
        VlUnpacked<IData/*31:0*/, 32> Main__DOT__cpucore__DOT__ID__DOT__reg___DOT__rf;
        VlUnpacked<IData/*31:0*/, 32> Main__DOT__cpucore__DOT__ID__DOT__reg___DOT__difftest__DOT__regs;
        VlUnpacked<IData/*31:0*/, 5> Main__DOT__cpucore__DOT__ID__DOT__reg___DOT__difftest__DOT__csr;
        VlUnpacked<CData/*0:0*/, 2> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<1> __VactTriggered;
    VlTriggerVec<1> __VnbaTriggered;

    // INTERNAL VARIABLES
    VMain__Syms* const vlSymsp;

    // CONSTRUCTORS
    VMain___024root(VMain__Syms* symsp, const char* v__name);
    ~VMain___024root();
    VL_UNCOPYABLE(VMain___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
