// Generated by CIRCT unknown git version
module ALU(	// <stdin>:2:10
  input         clock,
                reset,
  input  [11:0] io_alu_op,
  input  [31:0] io_src1,
                io_src2,
  output [31:0] io_res);

  wire        add_sub = io_alu_op[1] | io_alu_op[2] | io_alu_op[3];	// ALU.scala:16:32, :17:32, :18:32, :28:36
  wire [31:0] or_res = io_src1 | io_src2;	// ALU.scala:33:27
  wire [62:0] sll_res = {31'h0, io_src1} << io_src2[4:0];	// ALU.scala:36:{27,37}
  wire [63:0] sr_res = {{32{io_src1[31] & io_alu_op[10]}}, io_src1} >> io_src2[4:0];	// ALU.scala:25:32, :30:26, :36:37, :37:39, :38:21, Bitwise.scala:77:12, Cat.scala:33:92
  assign io_res = (io_alu_op[10] | io_alu_op[9] ? sr_res[31:0] : 32'h0) | (io_alu_op[0] | io_alu_op[1] ?
                io_src1 + ({32{add_sub}} ^ io_src2) + {31'h0, add_sub} : 32'h0) | (io_alu_op[4] ? io_src1 &
                io_src2 : 32'h0) | (io_alu_op[6] ? or_res : 32'h0) | (io_alu_op[5] ? ~or_res : 32'h0) |
                (io_alu_op[7] ? io_src1 ^ io_src2 : 32'h0) | (io_alu_op[8] ? sll_res[31:0] : 32'h0) |
                (io_alu_op[11] ? io_src2 : 32'h0);	// <stdin>:2:10, ALU.scala:15:28, :16:32, :19:32, :20:32, :21:32, :22:32, :23:32, :24:32, :25:32, :26:32, :28:36, :29:{33,62}, :32:27, :33:27, :34:19, :35:27, :36:27, :38:21, :42:17, :48:17, Bitwise.scala:77:12, Mux.scala:27:73
endmodule

