// Generated by CIRCT unknown git version
module EX_stage(	// <stdin>:2:10
  input         clock,
                reset,
  input  [31:0] a_alu_src1,
                a_alu_src2,
  input  [11:0] a_alu_op,
  output        b_c);

  assign b_c = a_alu_op[1];	// <stdin>:2:10, EX_stage.scala:11:20
endmodule

