// Generated by CIRCT unknown git version
module EX_stage(	// <stdin>:75:10
  input        clock,
               reset,
  input [31:0] a_alu_src1,
               a_alu_src2,
  input [11:0] a_alu_op);

endmodule

