// Generated by CIRCT unknown git version
module IF_stage(	// <stdin>:2:10
  input         clock,
                reset,
  input  [31:0] inst_sram_rdata,
  output [31:0] io_inst);

  assign io_inst = inst_sram_rdata;	// <stdin>:2:10
endmodule

