// Generated by CIRCT unknown git version
// external module Memory

module mem(	// <stdin>:11:10
  input         clock,
                reset,
  input  [63:0] io_Raddr,
                io_Waddr,
                io_Wdata,
  input  [7:0]  io_Wmask,
  input         io_MemWrite,
  output [63:0] io_Rdata);

  Memory pmem (	// Mem.scala:15:22
    .Raddr    (io_Raddr),
    .Waddr    (io_Waddr),
    .Wdata    (io_Wdata),
    .Wmask    (io_Wmask),
    .MemWrite (io_MemWrite),
    .Rdata    (io_Rdata)
  );
endmodule


// ----- 8< ----- FILE "./vsrc/Memory.v" ----- 8< -----


import "DPI-C" function void pmem_read(
  input longint Raddr, output longint Rdata);
import "DPI-C" function void pmem_write(
  input longint Waddr, input longint Wdata, input byte Wmask);
module Memory (Raddr,Rdata,Waddr,Wdata,Wmask,MemWrite);
 input [63:0] Raddr,Waddr,Wdata;
 input [7:0] Wmask;
 input MemWrite;
 output [63:0] Rdata;
 always @(*) begin
 pmem_read(Raddr, Rdata);
 if(MemWrite)
  pmem_write(Waddr, Wdata, Wmask);
 end
endmodule
    

// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----

vsrc/vsrc/Memory.v
