// Generated by CIRCT unknown git version
// external module mem

module rdmem(	// <stdin>:11:10
  input         clock,
                reset,
  input  [63:0] mem_io_Raddr,
                mem_io_Waddr,
                mem_io_Wdata,
  input  [7:0]  mem_io_Wmask,
  input         mem_io_MemWrite,
  output [63:0] mem_io_Rdata);

  mem mem (	// Mem1.scala:8:25
    .Raddr    (mem_io_Raddr),
    .Waddr    (mem_io_Waddr),
    .Wdata    (mem_io_Wdata),
    .Wmask    (mem_io_Wmask),
    .MemWrite (mem_io_MemWrite),
    .Rdata    (mem_io_Rdata)
  );
endmodule


// ----- 8< ----- FILE "./vsrc/Mem.v" ----- 8< -----


import "DPI-C" function void pmem_read(
  input longint Raddr, output longint Rdata);
import "DPI-C" function void pmem_write(
  input longint Waddr, input longint Wdata, input byte Wmask);
module Mem (Raddr,Rdata,Waddr,Wdata,Wmask,MemWrite);
 input [63:0] Raddr,Waddr,Wdata;
 input [7:0] Wmask;
 input MemWrite;
 output [63:0] Rdata;
 always @(*) begin
 pmem_read(Raddr, Rdata);
 if(MemWrite)
  pmem_write(Waddr, Wdata, Wmask);
 end
endmodule
    

// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----

vsrc/vsrc/Mem.v
