// Generated by CIRCT unknown git version
// external module dmem

module rdmem(	// <stdin>:7:10
  input         clock,
                reset,
  input  [31:0] mem_io_wio_rdata,
  output        mem_io_rio_en,
  output [3:0]  mem_io_rio_we,
  output [31:0] mem_io_rio_addr,
                mem_io_rio_wdata,
  output [3:0]  mem_io_rio_wstrb);

  dmem mem (	// Mem.scala:41:25
    .wio_rdata (mem_io_wio_rdata),
    .rio_en    (mem_io_rio_en),
    .rio_we    (mem_io_rio_we),
    .rio_addr  (mem_io_rio_addr),
    .rio_wdata (mem_io_rio_wdata),
    .rio_wstrb (mem_io_rio_wstrb)
  );
endmodule


// ----- 8< ----- FILE "./vsrc/memory.v" ----- 8< -----

module mem(
	input en,
	input [3:0]   we,
	input [31:0]  addr,
	input [31:0]  wdata,
	input [4:0]   wstrb,
	output [31:0] rdata
);
import "DPI-C" function void pmem_read(
	input longint raddr, output longint rdata);
import "DPI-C" function void pmem_write(
	input longint waddr, input longint wdata, input byte wmask);
wire [63:0] rdata;
always @(*) begin
	pmem_read(raddr, rdata);
	pmem_write(waddr, wdata, wmask);
end

	

// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----

vsrc/vsrc/memory.v
