// Generated by CIRCT unknown git version
module test(	// <stdin>:2:10
  input        clock,
               reset,
  input  [2:0] in,
  output       out);

  assign out = in == 3'h1 & in == 3'h2 & in == 3'h5;	// <stdin>:2:10, tool.scala:36:{23,31}
endmodule

