// Generated by CIRCT unknown git version
module test(	// <stdin>:2:10
  input        clock,
               reset,
  input  [2:0] in,
  output       out);

  assign out = in[0];	// <stdin>:2:10, te.scala:14:9
endmodule

